# -*- coding: utf-8 -*-
"""Book_Atraso_06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162l1NmxbJKx-yph5vxRMNjrP1GNlkByx

# Iniciando o Spark
"""

from google.colab import drive
drive.mount('/content/gdrive')

from pyspark.sql import SparkSession
import os
import pytz
from datetime import datetime

spark = SparkSession.builder.appName("tabelas").getOrCreate()

spark.conf.set("spark.sql.session.timeZone", "America/Sao_Paulo")
spark.conf.set("spark.sql.legacy.timeParserPolicy", "LEGACY")

spark

"""# Instalando bibliotecas"""

import os
import sys
import pytz
import numpy as np
import datetime
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql.functions import udf,split, lpad, concat_ws,to_timestamp,col,coalesce
from datetime import datetime
from datetime import timedelta
from datetime import date
from dateutil.relativedelta import relativedelta
from pyspark.sql.types import *
from pyspark.sql.functions import count, avg, to_date
from pyspark.sql import functions as F

"""#Configuração do pipeline( contem configuração do spark e os paths para serem alterados)

"""

# caminhos dos arquivos

PATH_TABELA_BUREAU ="/content/gdrive/MyDrive/Raw Hackathon PoD 2025/base_score_bureau_movel_full"
PATH_TABELA_CADASTRO = "/content/gdrive/MyDrive/Raw Hackathon PoD 2025/base_dados_cadastrais"
PATH_BASE_TELCO       = "/content/gdrive/MyDrive/Raw Hackathon PoD 2025/base_telco"
PATH_BASE_RECARGA     = "/content/gdrive/MyDrive/Raw Hackathon PoD 2025/bases_recarga/BI_FP_ASS_RECARGA_CMV_NOVA"
PATH_BASE_BOOK_ATRASO = "/content/gdrive/MyDrive/Raw Hackathon PoD 2025/book_atraso/dados_faturamento"
PATH_BASE_BOOK_PAGAMENTO ="/content/gdrive/MyDrive/Raw Hackathon PoD 2025/book_pagamento/dados_pagamento"

BASE_PATH_RECARGA = "/content/gdrive/MyDrive/Raw Hackathon PoD 2025/bases_recarga"

PATH_DIMENSOES_RECARGA = {
    "CANAL_AQUISICAO": f"{BASE_PATH_RECARGA}/BI_DIM_CANAL_AQUISICAO_CREDITO.csv",
    "FORMA_PAGAMENTO": f"{BASE_PATH_RECARGA}/BI_DIM_FORMA_PAGAMENTO.csv",
    "INSTITUICAO": f"{BASE_PATH_RECARGA}/BI_DIM_INSTITUICAO.csv",
    "PLATAFORMA": f"{BASE_PATH_RECARGA}/BI_DIM_PLATAFORMA.csv",
    "PROMOCAO": f"{BASE_PATH_RECARGA}/BI_DIM_PROMOCAO_CREDITO.csv",
    "STATUS_PLATAFORMA": f"{BASE_PATH_RECARGA}/BI_DIM_STATUS_PLATAFORMA.csv",
    "TECNOLOGIA": f"{BASE_PATH_RECARGA}/BI_DIM_TECNOLOGIA.csv",
    "TIPO_CREDITO": f"{BASE_PATH_RECARGA}/BI_DIM_TIPO_CREDITO.csv",
    "TIPO_INSERCAO": f"{BASE_PATH_RECARGA}/BI_DIM_TIPO_INSERCAO.csv",
    "TIPO_RECARGA": f"{BASE_PATH_RECARGA}/BI_DIM_TIPO_RECARGA.csv",
}


PATH_DIMENSOES_BOOK_ATRASO = "/content/gdrive/MyDrive/Raw Hackathon PoD 2025/book_atraso/BI_DIM_TIPO_FATURAMENTO.csv"

# Csvs da tabela recarga

BASE_PATH_RECARGA = "/content/gdrive/MyDrive/Raw Hackathon PoD 2025/bases_recarga"

DIMENSOES_RECARGA = {
    "CANAL_AQUISICAO_CREDITO": "BI_DIM_CANAL_AQUISICAO_CREDITO.csv",
    "FORMA_PAGAMENTO": "BI_DIM_FORMA_PAGAMENTO.csv",
    "INSTITUICAO": "BI_DIM_INSTITUICAO.csv",
    "PLANO_PRECO": "BI_DIM_PLANO_PRECO.csv",
    "PLATAFORMA": "BI_DIM_PLATAFORMA.csv",
    "PROMOCAO_CREDITO": "BI_DIM_PROMOCAO_CREDITO.csv",
    "STATUS_PLATAFORMA": "BI_DIM_STATUS_PLATAFORMA.csv",
    "TECNOLOGIA": "BI_DIM_TECNOLOGIA.csv",
    "TIPO_CREDITO": "BI_DIM_TIPO_CREDITO.csv",
    "TIPO_INSERCAO": "BI_DIM_TIPO_INSERCAO.csv",
    "TIPO_RECARGA": "BI_DIM_TIPO_RECARGA.csv",
}


dfs_dim_recarga = {}

for nome_dim, arquivo in DIMENSOES_RECARGA.items():
    path = f"{BASE_PATH_RECARGA}/{arquivo}"

    dfs_dim_recarga[nome_dim] = (
        spark.read
        .option("header", True)
        .option("sep", ",")
        .option("inferSchema", True)
        .csv(path)
    )

df_CANAL_AQUISICAO_CREDITO = dfs_dim_recarga["CANAL_AQUISICAO_CREDITO"]
df_FORMA_PAGAMENTO        = dfs_dim_recarga["FORMA_PAGAMENTO"]
df_INSTITUICAO            = dfs_dim_recarga["INSTITUICAO"]
df_PLANO_PRECO            = dfs_dim_recarga["PLANO_PRECO"]
df_PLATAFORMA             = dfs_dim_recarga["PLATAFORMA"]
df_PROMOCAO_CREDITO       = dfs_dim_recarga["PROMOCAO_CREDITO"]
df_STATUS_PLATAFORMA      = dfs_dim_recarga["STATUS_PLATAFORMA"]
df_TECNOLOGIA              = dfs_dim_recarga["TECNOLOGIA"]
df_TIPO_CREDITO           = dfs_dim_recarga["TIPO_CREDITO"]
df_TIPO_INSERCAO          = dfs_dim_recarga["TIPO_INSERCAO"]
df_TIPO_RECARGA           = dfs_dim_recarga["TIPO_RECARGA"]

# cadastro
df_cadastro = spark.read.parquet(PATH_TABELA_CADASTRO)
df_cadastro.createOrReplaceTempView("df_cadastro")

# bureau
df_bureau = spark.read.parquet(PATH_TABELA_BUREAU)
df_bureau.createOrReplaceTempView("df_bureau")

# telco
df_base_telco = spark.read.parquet(PATH_BASE_TELCO)
df_base_telco.createOrReplaceTempView("df_base_telco")

# recarga
df_recarga = spark.read.parquet(PATH_BASE_RECARGA)
df_recarga.createOrReplaceTempView("df_recarga")

# book atraso
df_book_atraso = spark.read.parquet(PATH_BASE_BOOK_ATRASO)
df_book_atraso.createOrReplaceTempView("df_book_atraso")

# book pagamento
df_book_pagamento = spark.read.parquet(PATH_BASE_BOOK_PAGAMENTO)
df_book_pagamento.createOrReplaceTempView("df_book_pagamento")

import os
import sys
import pytz
import numpy as np
import datetime
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql.functions import udf,split, lpad, concat_ws,to_timestamp,col,coalesce
from datetime import datetime
from datetime import timedelta
from datetime import date
from dateutil.relativedelta import relativedelta
from pyspark.sql.types import *
from pyspark.sql.functions import count, avg, to_date
from pyspark.sql import functions as F

"""# Book Atraso"""

# book atraso
df_book_atraso = spark.read.parquet(PATH_BASE_BOOK_ATRASO)
df_book_atraso.createOrReplaceTempView("df_book_atraso")

# Alterando o datatype
df_book_atraso = spark.sql("""
SELECT
    CAST(NUM_CPF AS STRING) AS NUM_CPF,
    DAT_REFERENCIA AS DAT_REFERENCIA,
    CAST(NUM_FATURA_HASH AS STRING) AS NUM_FATURA_HASH,
    CAST(NUM_ENT_SEQ_FATURA AS INT) AS NUM_ENT_SEQ_FATURA,
    CAST(CONTRATO AS BIGINT) AS CONTRATO,
    CAST(DW_UN_NEGOCIO AS INT) AS DW_UN_NEGOCIO,
    CAST(DW_HIS_PONTO_VENDA_COMTA AS BIGINT) AS DW_HIS_PONTO_VENDA_COMTA,
    CAST(DW_NUM_CLIENTE AS BIGINT) AS DW_NUM_CLIENTE,
    CAST(DW_AREA AS INT) AS DW_AREA,
    CAST(DW_CICLO AS INT) AS DW_CICLO,
    CAST(DW_TIPO_CLIENTE_CONTA AS INT) AS DW_TIPO_CLIENTE_CONTA,
    CAST(DW_OFERTA AS INT) AS DW_OFERTA,
    CAST(DW_FAIXA_AGING_FATURA AS INT) AS DW_FAIXA_AGING_FATURA,
    CAST(DW_FAIXA_AGING_DIVIDA AS INT) AS DW_FAIXA_AGING_DIVIDA,
    CAST(DW_FAIXA_TEMPO_BASE AS INT) AS DW_FAIXA_TEMPO_BASE,
    CAST(DW_FAIXA_AGING_PROX_FECH AS INT) AS DW_FAIXA_AGING_PROX_FECH,
    CAST(DW_TIPO_FATURAMENTO AS INT) AS DW_TIPO_FATURAMENTO,
    CAST(COD_PLATAFORMA AS STRING) AS COD_PLATAFORMA,

    -- todas as DAT_* como STRING
    CAST(DAT_CRIACAO_REGISTRO_TRANS AS STRING) AS DAT_CRIACAO_REGISTRO_TRANS,
    CAST(DAT_ALTERACAO_REGISTRO_TRANS AS STRING) AS DAT_ALTERACAO_REGISTRO_TRANS,
    CAST(DAT_CANCELAMENTO_FAT AS STRING) AS DAT_CANCELAMENTO_FAT,
    CAST(DAT_ORIGINAL_VCTO_FAT AS STRING) AS DAT_ORIGINAL_VCTO_FAT,
    CAST(DAT_ALTERACAO_VCTO_FAT AS STRING) AS DAT_ALTERACAO_VCTO_FAT,
    CAST(DAT_CRIACAO_FAT AS STRING) AS DAT_CRIACAO_FAT,
    CAST(DAT_VENCIMENTO_FAT AS STRING) AS DAT_VENCIMENTO_FAT,
    CAST(DAT_STATUS_FAT AS STRING) AS DAT_STATUS_FAT,
    CAST(DAT_MIN_VENCIMENTO_FAT AS STRING) AS DAT_MIN_VENCIMENTO_FAT,
    CAST(DAT_ATIVACAO_CONTA_CLI AS STRING) AS DAT_ATIVACAO_CONTA_CLI,
    CAST(DAT_CRIACAO_DW AS STRING) AS DAT_CRIACAO_DW,

    CAST(NUM_BILL_SEQ_FAT AS INT) AS NUM_BILL_SEQ_FAT,
    CAST(NUM_SEQ_ACORDO_FAT AS INT) AS NUM_SEQ_ACORDO_FAT,

    CAST(IND_ISENCAO_COB_FAT AS STRING) AS IND_ISENCAO_COB_FAT,
    CAST(IND_WO AS STRING) AS IND_WO,
    CAST(IND_PDD AS STRING) AS IND_PDD,
    CAST(IND_PCCR AS STRING) AS IND_PCCR,
    CAST(IND_ACA AS STRING) AS IND_ACA,
    CAST(IND_PRIMEIRA_FAT AS STRING) AS IND_PRIMEIRA_FAT,
    CAST(IND_FRAUDE AS STRING) AS IND_FRAUDE,

    CAST(VAL_FAT_LIQUIDO AS DECIMAL(18,2)) AS VAL_FAT_LIQUIDO,
    CAST(VAL_FAT_BRUTO AS DECIMAL(18,2)) AS VAL_FAT_BRUTO,
    CAST(VAL_FAT_CREDITO AS DECIMAL(18,2)) AS VAL_FAT_CREDITO,
    CAST(VAL_FAT_AJUSTE AS DECIMAL(18,2)) AS VAL_FAT_AJUSTE,
    CAST(VAL_FAT_BRUTO_BC AS DECIMAL(18,2)) AS VAL_FAT_BRUTO_BC,
    CAST(VAL_FAT_PAGAMENTO_BRUTO AS DECIMAL(18,2)) AS VAL_FAT_PAGAMENTO_BRUTO,
    CAST(VAL_FAT_ABERTO AS DECIMAL(18,2)) AS VAL_FAT_ABERTO,
    CAST(VAL_FAT_ABERTO_LIQ AS DECIMAL(18,2)) AS VAL_FAT_ABERTO_LIQ,
    CAST(VAL_MULTA_JUROS AS DECIMAL(18,2)) AS VAL_MULTA_JUROS,
    CAST(VAL_MULTA_CANCELAMENTO AS DECIMAL(18,2)) AS VAL_MULTA_CANCELAMENTO,
    CAST(VAL_PARC_APARELHO_LIQ AS DECIMAL(18,2)) AS VAL_PARC_APARELHO_LIQ,
    CAST(VAL_FAT_LIQ_JM_MC AS DECIMAL(18,2)) AS VAL_FAT_LIQ_JM_MC
FROM df_book_atraso
""")

#Criando coluna SAFRA, VAI SER USADO OS DADOS DA COLUNA "DAT_REFERENCIA",
#PODE SER MUDADO DE ACORDO COM A NECESSIDADE DO NEGOCIO
df_book_atraso.createOrReplaceTempView("df_book_atraso")

df_book_atraso = spark.sql("""
SELECT
    *,
    TO_DATE(
        TO_TIMESTAMP(
            UPPER(DAT_REFERENCIA),
            'ddMMMyyyy:HH:mm:ss'
        )
    ) AS SAFRA,
    YEAR(
        TO_TIMESTAMP(
            UPPER(DAT_REFERENCIA),
            'ddMMMyyyy:HH:mm:ss'
        )
    ) AS SAFRA_ANO,
    MONTH(
        TO_TIMESTAMP(
            UPPER(DAT_REFERENCIA),
            'ddMMMyyyy:HH:mm:ss'
        )
    ) AS SAFRA_MES
FROM df_book_atraso
""")

# colocar indentificador nas variaveis da tabela BOOK ATRASO
for c in df_book_atraso.columns:
    df_book_atraso = df_book_atraso.withColumnRenamed(
        c, f"BOOK_ATRASO_{c}"
    )

df_book_atraso.createOrReplaceTempView("df_book_atraso_prefixed_final")

"""# Criação do Book de Variáveis

Book de Atraso

## Objetivo
Este book consolida informações de **inadimplência por CPF**, de forma limpa e objetiva, permitindo identificar:
- Existência de atraso
- Persistência do atraso ao longo do tempo
- Indícios de risco financeiro
- Complexidade do cliente (mais de um número associado)

O foco é **facilidade de consumo**, **uso em modelos preditivos** e **leitura rápida por negócio**.

---

- **1 linha por CPF por SAFRA (mês)**

---

##  Chaves
- `BOOK_ATRASO_NUM_CPF`
- `BOOK_ATRASO_SAFRA`

---

## Flags de Comportamento

| Coluna | Descrição |
|------|----------|
| `FLG_POSSUI_MAIS_DE_UM_NUMERO` | Indica se o CPF possui mais de um número de telefone associado (1 = sim, 0 = não) |
| `FLG_POSSUI_ATRASO_MES` | Indica se houve valor em aberto no mês |
| `FLG_POSSUI_MULTA_MES` | Indica se houve cobrança de multa ou juros no mês |

---

## Métricas de Intensidade do Atraso

Valores acumulados de atraso ao longo do tempo, permitindo avaliar **recorrência e gravidade** da inadimplência.

| Coluna | Descrição |
|------|----------|
| `VAL_ATRASO_U1M` | Valor em atraso no mês corrente |
| `VAL_ATRASO_U3M` | Soma do atraso nos últimos 3 meses |
| `VAL_ATRASO_U6M` | Soma do atraso nos últimos 6 meses |
| `VAL_ATRASO_U9M` | Soma do atraso nos últimos 9 meses |
| `VAL_ATRASO_U12M` | Soma do atraso nos últimos 12 meses |


Um CPF pode possuir **mais de um número de telefone**
- Atraso é caracterizado por `VAL_FAT_ABERTO_LIQ > 0`
- Multa é caracterizada por `VAL_MULTA_JUROS > 0`
"""

df_book_atraso = spark.sql("""

WITH base_cpf_mes AS (
    SELECT
        BOOK_ATRASO_NUM_CPF,
        BOOK_ATRASO_SAFRA,

        COUNT(DISTINCT BOOK_ATRASO_DW_NUM_CLIENTE) AS QTD_NUMEROS_CPF,

        SUM(BOOK_ATRASO_VAL_FAT_BRUTO) AS VAL_ATRASO_MES,
        SUM(BOOK_ATRASO_VAL_MULTA_JUROS)    AS VAL_MULTA_JUROS_MES
    FROM df_book_atraso_prefixed_final
    GROUP BY
        BOOK_ATRASO_NUM_CPF,
        BOOK_ATRASO_SAFRA
),

book_atraso_janelas AS (
    SELECT
        BOOK_ATRASO_NUM_CPF,
        BOOK_ATRASO_SAFRA,

        -- Flags simples
        CASE WHEN QTD_NUMEROS_CPF > 1 THEN 1 ELSE 0 END
            AS FLG_POSSUI_MAIS_DE_UM_NUMERO,

        CASE WHEN VAL_ATRASO_MES > 0 THEN 1 ELSE 0 END
            AS FLG_POSSUI_ATRASO_MES,

        CASE WHEN VAL_MULTA_JUROS_MES > 0 THEN 1 ELSE 0 END
            AS FLG_POSSUI_MULTA_MES,

        -- Intensidade do atraso
        VAL_ATRASO_MES AS VAL_ATRASO_U1M,

        SUM(VAL_ATRASO_MES) OVER (
            PARTITION BY BOOK_ATRASO_NUM_CPF
            ORDER BY BOOK_ATRASO_SAFRA
            ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
        ) AS VAL_ATRASO_U3M,

        SUM(VAL_ATRASO_MES) OVER (
            PARTITION BY BOOK_ATRASO_NUM_CPF
            ORDER BY BOOK_ATRASO_SAFRA
            ROWS BETWEEN 5 PRECEDING AND CURRENT ROW
        ) AS VAL_ATRASO_U6M,

        SUM(VAL_ATRASO_MES) OVER (
            PARTITION BY BOOK_ATRASO_NUM_CPF
            ORDER BY BOOK_ATRASO_SAFRA
            ROWS BETWEEN 8 PRECEDING AND CURRENT ROW
        ) AS VAL_ATRASO_U9M,

        SUM(VAL_ATRASO_MES) OVER (
            PARTITION BY BOOK_ATRASO_NUM_CPF
            ORDER BY BOOK_ATRASO_SAFRA
            ROWS BETWEEN 11 PRECEDING AND CURRENT ROW
        ) AS VAL_ATRASO_U12M

    FROM base_cpf_mes
)

SELECT * FROM book_atraso_janelas
""")

df_book_atraso.show(20, truncate=False)