# -*- coding: utf-8 -*-
"""camada_raw_base_recargas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMPcUx3k3hgildEmNYp7-_gu66O23Jtu

# Iniciando o Spark
"""

from pyspark.sql import SparkSession
import os
import pytz
from datetime import datetime

spark = SparkSession.builder.appName("raw_base_recargas").getOrCreate()

"""# Instalando bibliotecas"""

import os
import sys
import pytz
import numpy as np
import datetime
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql.functions import udf, lpad, translate
from datetime import datetime
from datetime import timedelta
from datetime import date
from dateutil.relativedelta import relativedelta
from pyspark.sql.types import *
from pyspark.sql.functions import count, avg

"""# Funções auxiliares e variáveis"""

# Função de log
def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " >>>"

# Timestamp de processamento (com hora/minuto/segundo)
agora = datetime.now(pytz.timezone('America/Sao_Paulo'))
dthproc = agora.strftime("%Y%m%d%H%M%S")

# Data da execução (AAAAmmdd)
PROCESS_DATE = datetime.now().strftime("%Y%m%d")

# Período de referência (AAAAmm)
REF_PERIOD = datetime.now().strftime("%Y%m")

# Buckets e nomes de saída
bucket_base = "base_telco"
bucket_trusted = f"s3://meu-bucket/{PROCESS_DATE}/0003_trusted/{bucket_base}"
bucket_raw = f"s3://meu-bucket/{PROCESS_DATE}/0002_raw/{bucket_base}"
bucket_control = f"s3://meu-bucket/{PROCESS_DATE}/0005_control/{bucket_base}"
output_trusted = f"trusted_{bucket_base}"

# Prints para conferência
print("PROCESS_DATE:", PROCESS_DATE)
print("REF_PERIOD:", REF_PERIOD)
print("dthproc:", dthproc)
print("bucket_trusted:", bucket_trusted)
print("bucket_raw:", bucket_raw)
print("bucket_control:", bucket_control)

"""# Leitura da camada Raw"""

raw_path = os.path.join(bucket_raw , "base_recargas")
df_raw = spark.read.parquet(raw_path)
df_raw.createOrReplaceTempView("raw_base_recargas")

print(log(), "Registros na Raw:", df_raw.count())
df_raw.show(5, truncate=False)

"""# Análise de frequência de colunas"""

# decidir se ira colocar essa parte no projeto, pode usar processamento desnecessario
def Freq(pTabela, pColuna):
    qtd_total = pTabela.count()
    pTabela.createOrReplaceTempView("tab_input")

    frq = spark.sql(f"""
        SELECT
            {pColuna},
            COUNT(*) AS qtd_absoluto,
            ROUND(100*(COUNT(*) / {qtd_total}),2) AS qtd_percentual
        FROM tab_input
        GROUP BY {pColuna}
        ORDER BY {pColuna}
    """)

    qtd = frq.count()
    print("Quantidade de domínios:", qtd)
    if qtd > 500:
        frq.show(1000, truncate=False)
        return "Domínio muito granular"
    else:
        frq.show(qtd, truncate=False)
        print("Volumetria total:", qtd_total)
        return "Freq da coluna " + pColuna

# Exemplo de uso
Freq(df_Trusted_base_telco, "SAFRA_ANO")
Freq(df_Trusted_base_telco, "IsSetup")

"""# Leitura dos dados na camada Raw"""

raw_path = os.path.join(bucket_raw, "base_telco")
df_raw = spark.read.parquet(raw_path)
df_raw.createOrReplaceTempView("raw_base_telco")

print(log(), "Registros na Raw:", df_raw.count())
df_raw.show(5, truncate=False)

"""# Processamento tipagem para camada Trusted"""

df_bases_recarga = spark.sql(f"""
    SELECT
        '{REF_PERIOD}' AS ref,
        '{PROCESS_DATE}' AS ref_partition,
        '{dthproc}' AS ts_proc,
        '{dthproc}' AS ts_proc_partition,
        CAST(NUM_CPF AS STRING) AS NUM_CPF,
        CAST(DW_NUM_NTC AS STRING) AS DW_NUM_NTC,
        CAST(DW_NUM_CLIENTE AS STRING) AS DW_NUM_CLIENTE,
        CAST(DAT_INSERCAO_CREDITO AS STRING) AS DAT_INSERCAO_CREDITO,
        CAST(HOR_INSERCAO_CREDITO AS STRING) AS HOR_INSERCAO_CREDITO,
        CAST(COD_TECNOLOGIA_DW AS STRING) AS COD_TECNOLOGIA_DW,
        CAST(COD_CANAL_AQUISICAO AS INT) AS COD_CANAL_AQUISICAO,
        CAST(COD_TIPO_CREDITO AS STRING) AS COD_TIPO_CREDITO,
        CAST(COD_PROMOCAO AS INT) AS COD_PROMOCAO,
        CAST(VAL_CREDITO_INSERIDO AS FLOAT) AS VAL_CREDITO_INSERIDO,
        CAST(VAL_BONUS AS FLOAT) AS VAL_BONUS,
        CAST(VAL_REAL AS FLOAT) AS VAL_REAL,

        -- Plataforma e status
        CAST(COD_PLATAFORMA_ATU AS STRING) AS COD_PLATAFORMA_ATU,
        CAST(COD_STATUS_PLATAFORMA AS STRING) AS COD_STATUS_PLATAFORMA,
        CAST(IND_METODO_PAGAMENTO AS STRING) AS IND_METODO_PAGAMENTO,

        -- Plano e inserção
        CAST(DW_PLANO_TARIFACAO AS INT) AS DW_PLANO_TARIFACAO,
        CAST(DW_TIPO_RECARGA AS INT) AS DW_TIPO_RECARGA,
        CAST(DW_TIPO_INSERCAO AS INT) AS DW_TIPO_INSERCAO,
        CAST(DW_FORMA_PAGAMENTO AS INT) AS DW_FORMA_PAGAMENTO,
        CAST(DW_INSTITUICAO AS INT) AS DW_INSTITUICAO,

        -- Cartão
        CAST(COD_GRUPO_CARTAO AS STRING) AS COD_GRUPO_CARTAO,
        CAST(DSC_GRUPO_CARTAO_WPP AS STRING) AS DSC_GRUPO_CARTAO_WPP,

        -- SOS
        CAST(FLAG_SOS AS INT) AS FLAG_SOS,
        CAST(VALOR_SOS AS INT) AS VALOR_SOS

        FROM bases_recarga
""")

df_bases_recarga.printSchema()

df_bases_recarga.show()

"""# Salvar na camada Trusted"""

raw_path = os.path.join(bucket_raw, "base_telco")
df_raw = spark.read.parquet(raw_path)
df_raw.createOrReplaceTempView("raw_base_telco")

print(log(), "Registros na Raw:", df_raw.count())
df_raw.show(5, truncate=False)

"""# Controle de carga"""

raw_path = os.path.join(bucket_raw, "base_telco")
df_raw = spark.read.parquet(raw_path)
df_raw.createOrReplaceTempView("raw_base_telco")

print(log(), "Registros na Raw:", df_raw.count())
df_raw.show(5, truncate=False)

"""# Controle de processamento"""

raw_path = os.path.join(bucket_raw, "base_telco")
df_raw = spark.read.parquet(raw_path)
df_raw.createOrReplaceTempView("raw_base_telco")

print(log(), "Registros na Raw:", df_raw.count())
df_raw.show(5, truncate=False)