# -*- coding: utf-8 -*-
"""Trusted_base_telco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfgoFAqb_OZ82X97iEuM06OoG_bjULHy

# Iniciando o Spark
"""

!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("Trusted_base_telco") \
    .config('spark.ui.port', '4050') \
    .getOrCreate()

"""# Importando bibliotecas"""

import os
import sys
import time
import datetime
import pandas as pd
import numpy as np
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql import functions as F
from pyspark.sql.types import *
from pyspark.sql.functions import col, lit, udf, input_file_name
from datetime import datetime
from dateutil.relativedelta import relativedelta

"""# Funções"""

#Criar uma função log para registrar a data
def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') +' >>>'
dt_proc = datetime.now().strftime('%Y%m%d%H%M%S')
current_date = datetime.now().strftime('%Y%m%d')

"""# Importando os dados"""

raw_path = "s3://meu-bucket/raw/base_telco"

df_Trusted_base_telco = spark.read.parquet(raw_path)
df_Trusted_base_telco.createOrReplaceTempView("df_Trusted_base_telco")

"""# Processamento"""

# Carregar dados da camada raw em formato parquet e aplicar as transformações iniciais
df_Trusted_base_telco = spark.sql(f""" SELECT
     CAST(NUM_CPF AS STRING) AS NUM_CPF,
        '{dt_proc}' AS dt_Proc,
    CAST(SAFRA AS INT) AS SAFRA,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 1, 4) AS INT) AS SAFRA_ANO,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 5, 2) AS INT) AS SAFRA_MES,
    CAST(FLAG_INSTALACAO AS BOOLEAN) AS IsSetup,
    CAST(FPD AS BOOLEAN) AS IsFPD,
    CAST(PROD AS STRING) AS ProductDescription,
    CAST(flag_mig2 AS STRING) AS ProductMigration,
    CAST(var_26 AS FLOAT) AS Var26,
CAST(var_27 AS FLOAT) AS Var27,
CAST(var_28 AS FLOAT) AS Var28,
CAST(var_29 AS FLOAT) AS Var29,
CAST(var_30 AS FLOAT) AS Var30,
CAST(var_31 AS FLOAT) AS Var31,
CAST(var_32 AS FLOAT) AS Var32,
CAST(var_33 AS FLOAT) AS Var33,
CAST(var_34 AS FLOAT) AS Var34,
CAST(var_35 AS FLOAT) AS Var35,
CAST(var_36 AS FLOAT) AS Var36,
CAST(var_37 AS FLOAT) AS Var37,
CAST(var_38 AS FLOAT) AS Var38,
CAST(var_39 AS FLOAT) AS Var39,
CAST(var_40 AS FLOAT) AS Var40,
CAST(var_41 AS FLOAT) AS Var41,
CAST(var_42 AS FLOAT) AS Var42,
CAST(var_43 AS FLOAT) AS Var43,
CAST(var_44 AS FLOAT) AS Var44,
CAST(var_45 AS FLOAT) AS Var45,
CAST(var_46 AS FLOAT) AS Var46,
CAST(var_47 AS FLOAT) AS Var47,
CAST(var_48 AS FLOAT) AS Var48,
CAST(var_49 AS FLOAT) AS Var49,
CAST(var_50 AS FLOAT) AS Var50,
CAST(var_51 AS FLOAT) AS Var51,
CAST(var_52 AS FLOAT) AS Var52,
CAST(var_53 AS FLOAT) AS Var53,
CAST(var_54 AS FLOAT) AS Var54,
CAST(var_55 AS FLOAT) AS Var55,
CAST(var_56 AS FLOAT) AS Var56,
CAST(var_57 AS FLOAT) AS Var57,
CAST(var_58 AS FLOAT) AS Var58,
CAST(var_59 AS FLOAT) AS Var59,
CAST(var_60 AS FLOAT) AS Var60,
CAST(var_61 AS FLOAT) AS Var61,
CAST(var_62 AS FLOAT) AS Var62,
CAST(var_63 AS FLOAT) AS Var63,
CAST(var_64 AS FLOAT) AS Var64,
CAST(var_65 AS FLOAT) AS Var65,
CAST(var_66 AS FLOAT) AS Var66,
CAST(var_67 AS FLOAT) AS Var67,
CAST(var_68 AS FLOAT) AS Var68,
CAST(var_69 AS FLOAT) AS Var69,
CAST(var_70 AS FLOAT) AS Var70,
CAST(var_71 AS FLOAT) AS Var71,
CAST(var_72 AS FLOAT) AS Var72,
CAST(var_73 AS FLOAT) AS Var73,
CAST(var_74 AS FLOAT) AS Var74,
CAST(var_75 AS FLOAT) AS Var75,
CAST(var_76 AS FLOAT) AS Var76,
CAST(var_77 AS FLOAT) AS Var77,
CAST(var_78 AS FLOAT) AS Var78,
CAST(var_79 AS FLOAT) AS Var79,
CAST(var_80 AS FLOAT) AS Var80,
CAST(var_81 AS FLOAT) AS Var81,
CAST(var_82 AS FLOAT) AS Var82,
CAST(var_83 AS FLOAT) AS Var83,
CAST(var_84 AS FLOAT) AS Var84,
CAST(var_85 AS FLOAT) AS Var85,
CAST(var_86 AS FLOAT) AS Var86,
CAST(var_87 AS FLOAT) AS Var87,
CAST(var_88 AS FLOAT) AS Var88,
CAST(var_89 AS FLOAT) AS Var89,
CAST(var_90 AS FLOAT) AS Var90,
CAST(var_91 AS FLOAT) AS Var91,
CAST(var_92 AS FLOAT) AS Var92,
CAST(var_93 AS FLOAT) AS Var93
FROM df_Trusted_base_telco

""")

# Salvar tabela no bucket na camada Trusted
df_Trusted_base_telco.write \
    .mode("append") \
    .partitionBy("SAFRA") \
    .parquet("s3://meu-bucket/minha-pasta/df_trusted_base_telco")

"""# Leitura dos dados na tabela Trusted"""

# Ler os dados da tabela Trusted
df_Trusted_base_telco01 = spark.read.parquet("s3://meu-bucket/minha-pasta/df_trusted_base_telco")
df_Trusted_base_telco01.createOrReplaceTempView("df_Trusted_base_telco01")
df_Trusted_base_telco01.show()