# -*- coding: utf-8 -*-
"""local_testing_spark_book_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLtLYQH_nU7hxPXQy9gsftmSeGZcwXFT

# Iniciando o Spark
"""

## Bloco de codigo para instalar versao especifica dos pacotes
#!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Trusted_base_atraso") \
    .getOrCreate()

"""# Carregando pacotes"""

# Pacotes de manipulacao
import sys
import os
from pyspark.sql.functions import col, least

"""# Conexão ao repositório via OCI"""

# Buckets e nomes de saída nuvem = "oci://"
pasta_in = 'base_score_bureau_movel_full/'
pasta_out = 'Feature_store/'
namespace = "@grxzqsiaote6/"
bucket_trusted = f"oci://TRUSTED{namespace}{pasta_in}"
bucket_feature_store = f"oci://BOOKS_VARIAVEIS{namespace}{pasta_out}"

"""# Carregando databases

#### Base Dados Cadastrais
"""
## Carregando todos arquivos em parquet de uma pasta

df_bureau = spark.read.parquet(bucket_trusted)
#df_bureau.show()

#df_bureau.printSchema()

"""#### Ajustando os tipos de dados"""

# Caso precise podemos  ajustar os tipos de dados para otimizar a memoria e o correto processamento
# Mas já veio tratado da etapa de ingestão, então não é necessário fazer ajustes aqui, mas deixarei comentado como seria o processo
#df_bureau['Ano'] = df_bureau['Ano'].astype('int')
#df_bureau['Mes'] = df_bureau['Mes'].astype('int')
#df_bureau['FLAG_INSTALACAO'] = df_bureau['FLAG_INSTALACAO'].astype('bool')
#df_bureau['ProductDescription'] = df_bureau['ProductDescription'].astype('object') #PROD
#df_bureau['ProductMigration'] = df_bureau['ProductMigration'].astype('object') #flag_mig2
#df_bureau['SCORE_01'] = df_bureau['SCORE_01'].astype('float32')
#df_bureau['SCORE_02'] = df_bureau['SCORE_02'].astype('float32')
#df_bureau['FPD'] = df_bureau['FPD'].astype('Int64')
#df_bureau['NUM_CPF'] = df_bureau['NUM_CPF'].astype('object')
#df_bureau['SAFRA'] = df_bureau['SAFRA'].astype('int')

"""#### Feature Engineer

Iremos criar apenas as variáveis:
- Relação entre `SCORE_01` e `SCORE_02`
- Média entre `SCORE_01` e `SCORE_02`
- Diferenca entre `SCORE_01` e `SCORE_02`
- Minino entre `SCORE_01` e `SCORE_02`
"""

# Iremos criar as medidas descritas acima
df_bureau = df_bureau.select("*",
                             (col('SCORE_01') / col('SCORE_02')).alias('SCORE_RATE'),
                             ((col('SCORE_01') + col('SCORE_02')) / 2).alias('SCORE_AVG'),
                             (col('SCORE_02') - col('SCORE_01')).alias('SCORE_DIFF'),
                             least(col('SCORE_01'), col('SCORE_02')).alias('SCORE_MIN') #Menor valor
)
#df_bureau.show(4)

# Salvando o dataframe em parquet
df_bureau.write \
  .mode("overwrite") \
  .option("compression", "snappy") \
  .parquet(f"{bucket_feature_store}/book_variaveis_01")