# -*- coding: utf-8 -*-
"""camada_raw_base_dados_cadastrais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Tq7QvOtjy44sgdrLqhl5Lvk2IwQYw7s
"""

## Vloco de codigo para instalar versao especifica dos pacotes
##pip install pandas==1.5.3
##pip install numpy==1.24.3

#Importando as bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import missingno as msno

# Montando o drive no googlecolab
from google.colab import drive
drive.mount('/content/gdrive')

"""Funções

"""

def histplots_var_num(dataframe, bins=30):
    """
    Plota histogramas para todas as variáveis numéricas do dataframe fornecido
    em um painel com 3 gráficos por linha.

    :param dataframe: DataFrame para o qual os histogramas serão gerados.
    :param bins: Número de bins do histograma (default = 30).
    """
    # Seleciona apenas colunas numéricas
    numeric_columns = dataframe.select_dtypes(include=['float64', 'int64']).columns

    # Define o número de linhas com base no número de colunas numéricas
    nrows = len(numeric_columns) // 3 + (len(numeric_columns) % 3 > 0)

    # Inicializa o painel de gráficos
    fig, axes = plt.subplots(nrows=nrows, ncols=3, figsize=(14, nrows * 4))

    # Ajusta o layout
    plt.tight_layout(pad=4)

    # Configura estilo
    sns.set_style("whitegrid")

    # Plota histogramas para cada coluna numérica
    for i, column in enumerate(numeric_columns):
        sns.histplot(
            data=dataframe,
            x=column,
            bins=bins,
            kde=True,
            ax=axes[i // 3, i % 3],
            color="skyblue"
        )
        axes[i // 3, i % 3].set_title(
            f'{column}',
            fontdict={'fontsize': 14, 'fontweight': 'bold'}
        )
        axes[i // 3, i % 3].set_ylabel('')

    # Remove gráficos vazios (se houver)
    for j in range(i + 1, nrows * 3):
        fig.delaxes(axes.flatten()[j])

    # Adiciona título principal
    fig.suptitle(
        "Análise descritiva - Histogramas",
        fontsize=20,
        fontweight='bold',
        y=1.00
    )

# Metadados referente ao conjunto de dados
def gerar_metadado(dataframe):
    """
    Gera um dataframe contendo os Metadados do Dataframe fornecido.
    :param dataframe: Dataframe para o qual os metadados sao gerados:
    :return: Dataframe com os Metadados.
    """

    # Coleta de metadados basico
    metadado = pd.DataFrame({
        'nome_variavel': dataframe.columns,
        'tipo': dataframe.dtypes,
        'qtd_nulos': dataframe.isnull().sum(),
        'percente_nulls': round((dataframe.isnull().sum() / len(dataframe)) * 100, 2),
        'cardinalidade': dataframe.nunique()
    })

    metadado = metadado.sort_values(by='tipo')
    metadado = metadado.reset_index(drop=True)

    return metadado

# testando a função
metadado_df = gerar_metadado(df_base_dados_cadastrais)
metadado_df

"""Carregando o DataBase Dados_Cadastrais"""

path = '/content/gdrive/MyDrive/Raw Hackathon PoD 2025/base_dados_cadastrais'

all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.parquet')]
df_list = [pd.read_parquet(f, engine='pyarrow') for f in all_files]

df_base_dados_cadastrais = pd.concat(df_list, ignore_index=True)

# Mostrando fomato do banco de dados
df_base_dados_cadastrais.shape

#Carregando a base de dados para ver todas as variaveis
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

df_base_dados_cadastrais.head(20)

# Contando quantidades de dados nas variáveis
df_base_dados_cadastrais.count()

# Verificar o tipo de cada variável
df_base_dados_cadastrais.dtypes

for col in df_base_dados_cadastrais.columns:
    print(f'\n=== {col} ===')
    print(df_base_dados_cadastrais[col].astype(str).value_counts(dropna=False).head(30))

"""Todas variáveis estão como object, iremos colocar as denominações corretas para o ETL. A seguir iremos verificar a cardinalidade da var_xx para termos uma amostra de como os dados estão relacionados

- NUM_CPF: varchar
- SAFRA: int  (Criar duas nova colunas: Ano e Mes)
- FLAG_INSTALACAO: boolean
- FPD: boolean
- PROD: varchar
- flag_mig2: varchar
- STATUSRF: varchar
- DATADENASCIMENTO: date/varchar
- var_03: int
- var_02: int
- var_04: int
- var_05: int
- var_06: int
- var_07: float/int
- var_08: int
- var_09: int
- var_10: varchar (Pode ser denominada Profissão)
- var_11: float
- var_12: date
- var_13: misturada (date + int)
- var_14: int
- var_15: varchar (Pode ser denominada Estado)
- var_16: int
- var_17: int
- var_18: varchar
- var_19: varchar
- var_20: varchar
- var_21: varchar
- var_22: varchar (Pode ser denominadaa Cargo)
- var_23: varchar
- var_24: varchar
- var_25: varchar (Pode ser denominadaa Tipo_de_Auxilio)
- CEP_3_digitos: varchar/int

Analise univariada
Antes de seguirmos com a estruturação da tabela iremos analisar como os dados estão distribuidos. Seguiremos com a ordem das colunas com o menor para o maior percentual de nulos.

1 - NUM_CPF
"""

df_base_dados_cadastrais['NUM_CPF'].value_counts().sort_values(ascending=False)

"""Para o processo de ETL:

Nome: CPF
Transformar coluna em VARCHAR
Possuimos valores

2  -SAFRA
"""

df_base_dados_cadastrais['SAFRA'].value_counts().sort_index()

print('Inicio da safra: ', df_base_dados_cadastrais['SAFRA'].min())
print('Fim da safra: ', df_base_dados_cadastrais['SAFRA'].max())

"""Para o processo de ETL:

Nome: Safra
Transformar coluna em INT
Criar duas nova colunas: Ano e Mes

3  -FLAG_INSTALACAO
"""

df_base_dados_cadastrais['FLAG_INSTALACAO'].value_counts().sort_index()

dados = df_base_dados_cadastrais['FLAG_INSTALACAO'].value_counts()

plt.figure(figsize=(8, 6))
colors = ['#3498db', '#95a5a6']  # vermelho e verde
explode = (0.05, 0)  # destaca a primeira fatia

plt.pie(
    dados.values,
    labels=[f'{label}\n({value:,})' for label, value in zip(dados.index, dados.values)],
    autopct='%1.1f%%',
    colors=colors,
    explode=explode,
    startangle=90,
    textprops={'fontsize': 12, 'fontweight': 'bold'}
)

plt.title('Proporção de Instalações', fontsize=14, fontweight='bold', pad=20)
plt.axis('equal')
plt.tight_layout()
plt.show()

"""Para o processo ETL:

Nome: IsSetup ou IsInstallation

TIpo de dado: boolean

Criar variável descritiva

4 - FPD
"""

df_base_dados_cadastrais['FPD'].value_counts()

# Iremos filtrar os valores nulos da coluna FPD
df_base_dados_cadastrais[df_base_dados_cadastrais['FPD'].isnull()]

"""Todos os valores nulos da coluna FPD coincidem com valores nulos também na colima flag_mig_2.

Estas informações podem representar o mesmo dado ou terem valores atrelados entre si.

5 - PROD
"""

df_base_dados_cadastrais['PROD'].value_counts()

# Preparar dados agregados
dados_agregados = df_base_dados_cadastrais.groupby('PROD').size().reset_index(name='count')
dados_agregados = dados_agregados.sort_values('count', ascending=True)  # ordena para melhor visualização

plt.figure(figsize=(10, 8))
sns.barplot(
    data=dados_agregados,
    y='PROD',
    x='count',
    palette='viridis',
    orient='h'
)

plt.title('Contagem por PROD', fontsize=14, fontweight='bold', pad=20)
plt.xlabel('Quantidade', fontsize=12, fontweight='bold')
plt.ylabel('PROD', fontsize=12, fontweight='bold')

# Adicionar valores nas barras
for i, v in enumerate(dados_agregados['count']):
    plt.text(v + 0.5, i, str(v), va='center', fontsize=10)

plt.tight_layout()
plt.show()

"""Para o processo de ETL:

Nome: ProductDescription

Tipo de dado: Varchar

6 -flag_mig2
"""

df_base_dados_cadastrais['flag_mig2'].value_counts()

# Preparar dados agregados
dados_agregados = df_base_dados_cadastrais.groupby('flag_mig2').size().reset_index(name='count')
dados_agregados = dados_agregados.sort_values('count', ascending=True)  # ordena para melhor visualização

plt.figure(figsize=(10, 8))
sns.barplot(
    data=dados_agregados,
    y='flag_mig2',
    x='count',
    palette='viridis',
    orient='h'
)

plt.title('Contagem por PROD', fontsize=14, fontweight='bold', pad=20)
plt.xlabel('Quantidade', fontsize=12, fontweight='bold')
plt.ylabel('PROD', fontsize=12, fontweight='bold')

# Adicionar valores nas barras
for i, v in enumerate(dados_agregados['count']):
    plt.text(v + 0.5, i, str(v), va='center', fontsize=10)

plt.tight_layout()
plt.show()

"""Esta variavel contem os dados de CPFs que migraram de dados, sera necessario entender se este dado era o tipo de produto que ele contratou anteriormente ou se é o plano que ele entrou

Para o processo de ETL:

Nome: ProductMigration
Tipo de dado: Varchar

Verificando como estão os dados nulos
"""

# tratamento dos valores nulos
import missingno as msno
# msno.matrix(df_base_dados_cadastrais, color=(0.25, 0.5, 1))  # tom de azul claro
msno.bar(df_base_dados_cadastrais, color=(0.25, 0.5, 1))  # tom de azul claro

""" Analise das variaveis var_xx"""

## Transformando todos as colunas que começam com var_ sem numerico
for col in df_base_dados_cadastrais.columns:
    if col.startswith('var_'):
        df_base_dados_cadastrais[col] = pd.to_numeric(df_base_dados_cadastrais[col], errors='coerce')

## Agora aplicaremos a funcao de boxplot nas variaveis numericas
histplots_var_num(df_base_dados_cadastrais)