# -*- coding: utf-8 -*-
"""Trusted_base_dados_cadastrais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cF1uRfUH495C0O9knYe_NpUoQzuTrJl5

# Iniciando o Spark
"""

## Bloco de codigo para instalar versao especifica dos pacotes
#!pip install pyspark

#from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Trusted_base_dados_cadastrais") \
    .getOrCreate()

"""# Importando bibliotecas"""

import os
import pytz
import datetime
from datetime import datetime


"""# Funções auxiliares e variáveis"""

# Função de log
def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " >>>"

# Timestamp de processamento (com hora/minuto/segundo)
agora = datetime.now(pytz.timezone('America/Sao_Paulo'))
dthproc = agora.strftime("%Y%m%d%H%M%S")

# Data da execução (AAAAmmdd)
PROCESS_DATE = datetime.now().strftime("%Y%m%d")

# Período de referência (AAAAmm)
REF_PERIOD = datetime.now().strftime("%Y%m")

# Buckets e nomes de saída
bucket_base = "base_dados_cadastrais"
bucket_trusted = f"s3://hackathon_2025/{PROCESS_DATE}/0003_trusted/"
bucket_raw = f"s3://hackathon_2025/{PROCESS_DATE}/0002_raw/"
bucket_control = f"s3://hackathon_2025/{PROCESS_DATE}/0005_control/"
output_trusted = f"trusted_{bucket_base}"

# Prints para conferência
#print("PROCESS_DATE:", PROCESS_DATE)
#print("REF_PERIOD:", REF_PERIOD)
#print("dthproc:", dthproc)
#print("bucket_trusted:", bucket_trusted)
#print("bucket_raw:", bucket_raw)
#print("bucket_control:", bucket_control)

"""# Importando os dados"""

path_raw = os.path.join(bucket_raw, bucket_base)
df_raw = spark.read.parquet(path_raw)
df_raw.createOrReplaceTempView("df_Trusted_base_dados_cadastrais")

#print(log(), "Registros na Raw:", df_raw.count())
#df_raw.show(5, truncate=False)

"""# Processamento"""

#Alterando o datatype da base
df_base_dados_cadastrais = spark.sql(f"""
    SELECT

        CAST(NUM_CPF AS STRING) AS NUM_CPF,
        '{dthproc}' AS ts_proc,
        '{dthproc}' AS ts_proc_partition,
        CAST(SAFRA AS INT) AS SAFRA,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 1, 4) AS INT) AS SAFRA_ANO,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 5, 2) AS INT) AS SAFRA_MES,

        CAST(FLAG_INSTALACAO AS BOOLEAN) AS FLAG_INSTALACAO,
        CAST(FPD AS BOOLEAN) AS FPD,
        CAST(PROD AS STRING) AS PROD,
        CAST(flag_mig2 AS STRING) AS ProductMigration,
        CAST(STATUSRF AS STRING) AS STATUSRF,
        to_date(DATADENASCIMENTO, 'dd/MM/yyyy') AS DATA_DE_NASCIMENTO,
        to_date(var_12, 'dd/MM/yyyy') AS var_12,

        CAST(var_02 AS INT) AS var_02,
        CAST(var_03 AS INT) AS var_03,
        CAST(var_04 AS INT) AS var_04,
        CAST(var_05 AS INT) AS var_05,
        CAST(var_06 AS INT) AS var_06,
        CAST(var_07 AS FLOAT) AS var_07,
        CAST(var_08 AS INT) AS var_08,
        CAST(var_09 AS INT) AS var_09,
        CAST(var_10 AS STRING) AS Profissao,
        CAST(var_11 AS FLOAT) AS var_11,
        CAST(var_13 AS STRING) AS var_13,
        CAST(var_14 AS INT) AS var_14,
        CAST(var_15 AS STRING) AS Estado,
        CAST(var_16 AS INT) AS var_16,
        CAST(var_17 AS INT) AS var_17,
        CAST(var_18 AS STRING) AS var_18,
        CAST(var_19 AS STRING) AS var_19,
        CAST(var_20 AS STRING) AS var_20,
        CAST(var_21 AS STRING) AS var_21,
        CAST(var_22 AS STRING) AS Cargo,
        CAST(var_23 AS STRING) AS var_23,
        CAST(var_24 AS STRING) AS var_24,
        CAST(var_25 AS STRING) AS Tipo_de_Auxilio,
        CAST(CEP_3_digitos AS STRING) AS CEP_3_digitos

    FROM df_Trusted_base_dados_cadastrais

""")
df_base_dados_cadastrais.createOrReplaceTempView("lake_dados_cadastrais")
df_base_dados_cadastrais.cache()

#print(log(), "Registros Trusted:", df_base_dados_cadastrais.count())
#df_base_dados_cadastrais.printSchema()
#df_base_dados_cadastrais.show(5, truncate=False)

"""# Salvar na camada Trusted"""

# Salvar tabela no bucket na camada Trusted
path_trusted = os.path.join(bucket_trusted, output_trusted)
#print("Trusted path:", path_trusted)

df_base_dados_cadastrais.write \
    .partitionBy("SAFRA","ts_proc_partition") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(path_trusted)

"""# Controle de carga"""

controle = spark.sql(f"""
    SELECT
        '{output_trusted}' AS name_file,
        ts_proc,
        ts_proc_partition,
        COUNT(*) AS qtd_registros
    FROM lake_dados_cadastrais
    GROUP BY 1,2,3
""")

controle.createOrReplaceTempView("controle")
controle.cache()

#print(log(), "Registros controle:", controle.count())
#controle.show(truncate=False)

"""# Controle de processamento"""

path_control = os.path.join(bucket_control, f'tb_controle_processamento_{bucket_base}_trusted')
#print("Control path:", path_control)

controle.write \
    .mode("append") \
    .option("compression", "snappy") \
    .parquet(path_control)