# -*- coding: utf-8 -*-
"""local_testing_book_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNJmLs1BeWc_1Bkvvw3d1ginetpGDk0D
"""

## Bloco de codigo para instalar versao especifica dos pacotes
#!pip install pandas==1.5.3
#!pip install numpy==1.24.3

"""##### Carregando pacotes"""
# Pacotes de manipulacao
import pandas as pd

"""# Conexão ao repositório via OCI"""
# Buckets e nomes de saída nuvem = "oci://"
pasta_in = 'base_score_bureau_movel_full/'
pasta_out = 'Feature_store/'
namespace = "@grxzqsiaote6/"
bucket_trusted = f"oci://TRUSTED{namespace}{pasta_in}"
bucket_feature_store = f"oci://BOOKS_VARIAVEIS{namespace}{pasta_out}"


"""## Carregando databases
#### Base Dados Cadastrais
"""

## Carregando todos arquivos em parquet de uma pasta
df_bureau = pd.read_parquet(bucket_trusted, engine='pyarrow')

#df_bureau.head()

#df_bureau.info()

"""#### Confirmando o Ajuste dos tipos de dados"""
# Iremos ajustar os tipos de dados para otimizar a memoria e o correto processamento
df_bureau['Ano'] = df_bureau['Ano'].astype('int')
df_bureau['Mes'] = df_bureau['Mes'].astype('int')
df_bureau['FLAG_INSTALACAO'] = df_bureau['FLAG_INSTALACAO'].astype('bool')
df_bureau['ProductDescription'] = df_bureau['ProductDescription'].astype('object') #PROD
df_bureau['ProductMigration'] = df_bureau['ProductMigration'].astype('object') #flag_mig2
df_bureau['SCORE_01'] = df_bureau['SCORE_01'].astype('float32')
df_bureau['SCORE_02'] = df_bureau['SCORE_02'].astype('float32')
df_bureau['FPD'] = df_bureau['FPD'].astype('Int64')
df_bureau['NUM_CPF'] = df_bureau['NUM_CPF'].astype('object')
df_bureau['SAFRA'] = df_bureau['SAFRA'].astype('int')

"""#### Feature Engineer

Iremos criar apenas as variáveis:
- Relação entre `SCORE_01` e `SCORE_02`
- Média entre `SCORE_01` e `SCORE_02`
- Diferenca entre `SCORE_01` e `SCORE_02`
- Minino entre `SCORE_01` e `SCORE_02`
"""

# Iremos criar as medidas descritas acima
df_bureau['SCORE_RATE'] = df_bureau['SCORE_02'] / df_bureau['SCORE_01']
df_bureau['SCORE_AVG'] = (df_bureau['SCORE_01'] + df_bureau['SCORE_02']) / 2
df_bureau['SCORE_DIFF'] = df_bureau['SCORE_02'] - df_bureau['SCORE_01']
df_bureau['SCORE_MIN'] = df_bureau[['SCORE_01', 'SCORE_02']].min(axis=1)

# Salvando o dataframe em parquet
df_bureau.to_parquet(f"{bucket_feature_store}/book_variaveis_01.parquet", index=False)