# -*- coding: utf-8 -*-
"""Trusted_base_telco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLFIhHnXlMypn7y2_ym-maU9oD0abuKW

# Iniciando o Spark
"""

## Bloco de codigo para instalar versao especifica dos pacotes
#!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Trusted_base_telco") \
    .getOrCreate()

"""# Importando bibliotecas"""

import os
#import pytz
import datetime
from datetime import datetime

"""# Funções auxiliares e variáveis"""

# Função de log
def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " >>>"

# Timestamp de processamento (com hora/minuto/segundo)
#agora = datetime.now(pytz.timezone('America/Sao_Paulo'))
#dthproc = agora.strftime("%Y%m%d%H%M%S")
dthproc = datetime.now().strftime("%Y%m%d%H%M%S")

# Data da execução (AAAAmmdd)
PROCESS_DATE = datetime.now().strftime("%Y%m%d")

# Período de referência (AAAAmm)
REF_PERIOD = datetime.now().strftime("%Y%m")

# Buckets e nomes de saída
bucket_base = "base_telco"
#nuvem = "oci://"
namespace = "@grxzqsiaote6/"
pasta = 'base_telco/'

bucket_raw = f"oci://RAW{namespace}{pasta}"
bucket_trusted = f"oci://TRUSTED{namespace}{pasta}"
bucket_control = f"oci://CONTROL{namespace}{pasta}"
output_trusted = f"trusted_{bucket_base}"

# Prints para conferência
#print("PROCESS_DATE:", PROCESS_DATE)
#print("REF_PERIOD:", REF_PERIOD)
#print("dthproc:", dthproc)
#print("bucket_trusted:", bucket_trusted)
#print("bucket_raw:", bucket_raw)
#print("bucket_control:", bucket_control)

"""# Leitura dos dados na camada Raw"""

path_raw = bucket_raw
df_raw = spark.read.parquet(path_raw)
df_raw.createOrReplaceTempView("raw_base_telco")

#print(log(), "Registros na Raw:", df_raw.count())
#df_raw.show(5, truncate=False)

"""# Processamento tipagem para camada Trusted"""

df_trusted = spark.sql(f"""
    SELECT
        '{dthproc}' AS ts_proc,
        '{dthproc}' AS ts_proc_partition,
        CAST(NUM_CPF AS STRING) AS NUM_CPF,
        CAST(SAFRA AS INT) AS SAFRA,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 1, 4) AS INT) AS SAFRA_ANO,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 5, 2) AS INT) AS SAFRA_MES,
        CAST(FLAG_INSTALACAO AS BOOLEAN) AS IsSetup,
        CAST(FPD AS BOOLEAN) AS IsFPD,
        CAST(PROD AS STRING) AS ProductDescription,
        CAST(flag_mig2 AS STRING) AS ProductMigration,
        {",".join([f"CAST(var_{i} AS FLOAT) AS Var{i}" for i in range(26,94)])}
    FROM raw_base_telco
""")

df_trusted.createOrReplaceTempView("lake_base_telco")
#df_trusted.cache()

#print(log(), "Registros Trusted:", df_trusted.count())
#df_trusted.printSchema()
#df_trusted.show(5, truncate=False)

"""# Salvar na camada Trusted"""

path_trusted = bucket_trusted
#print("Trusted path:", path_trusted)

df_trusted.write \
    .partitionBy("ts_proc_partition","SAFRA") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(path_trusted)

"""# Controle de carga"""

controle = spark.sql(f"""
    SELECT
        '{output_trusted}' AS name_file,
        ts_proc,
        ts_proc_partition,
        COUNT(*) AS qtd_registros
    FROM lake_base_telco
    GROUP BY 1,2,3
""")

controle.createOrReplaceTempView("controle")
#controle.cache()

#print(log(), "Registros controle:", controle.count())
#controle.show(truncate=False)

"""# Controle de processamento"""

path_control = os.path.join(bucket_control, f'tb_controle_processamento_{output_trusted}_{PROCESS_DATE}')
#print("Control path:", path_control)

controle.write \
    .mode("append") \
    .option("compression", "snappy") \
    .parquet(path_control)