# -*- coding: utf-8 -*-
"""Trusted_base_bureau.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDu1uOZ6ob7P9i0ANph06pIa925iy9Fh

# Iniciando o Spark
"""

## Bloco de codigo para instalar versao especifica dos pacotes
#!pip install pyspark

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Pipeline de trusted bases Claro") \
    .getOrCreate()

"""# Importando bibliotecas"""
import os
#import pytz
import datetime
from datetime import datetime


"""# Funções auxiliares e variáveis"""
# Função de log
def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " >>>"

# Timestamp de processamento (com hora/minuto/segundo)
#agora = datetime.now(pytz.timezone('America/Sao_Paulo'))
#dthproc = agora.strftime("%Y%m%d%H%M%S")
dthproc = datetime.now().strftime("%Y%m%d%H%M%S")

# Data da execução (AAAAmmdd)
PROCESS_DATE = datetime.now().strftime("%Y%m%d")

# Período de referência (AAAAmm)
REF_PERIOD = datetime.now().strftime("%Y%m")

# Buckets e nomes de saída
bucket_bureau = "base_bureau"
#nuvem = "oci://"
namespace = "@grxzqsiaote6/"

# Base bureau

pasta_bureau = 'base_score_bureau_movel_full/'

bucket_raw_bureau = f"oci://RAW{namespace}{pasta_bureau}"
bucket_trusted_bureau = f"oci://TRUSTED{namespace}{pasta_bureau}"
bucket_control_bureau = f"oci://CONTROL{namespace}{pasta_bureau}"
output_bureau = f"trusted_{bucket_bureau}"

"""# Leitura dos dados na camada Raw"""

df_raw_bureau = spark.read.parquet(bucket_raw_bureau)
df_raw_bureau.createOrReplaceTempView("raw_base_bureau")

#print(log(), "Registros na Raw:", df_raw_bureau.count())
#df_raw_bureau.show(5, truncate=False)

"""# Processamento tipagem para camada Trusted"""

df_trusted_bureau = spark.sql(f"""
    SELECT
        '{dthproc}' AS ts_proc,
        '{dthproc}' AS ts_proc_partition,
        -- SAFRA convertida para DATE (primeiro dia do mês)
        CAST(CONCAT(SUBSTRING(SAFRA, 1, 4), '-', SUBSTRING(SAFRA, 5, 2), '-01') AS DATE) AS SAFRA,

        -- Ano e Mês extraídos da SAFRA
        CAST(SUBSTRING(SAFRA, 1, 4) AS INT) AS Ano,
        CAST(SUBSTRING(SAFRA, 5, 2) AS INT) AS Mes,

        CAST(FLAG_INSTALACAO AS BOOLEAN) AS IsInstallation,
        CAST(PROD AS STRING) AS ProductDescription,
        CAST(flag_mig2 AS STRING) AS ProductMigration,
        CAST(SCORE_01 AS FLOAT) AS Score01,
        CAST(SCORE_02 AS FLOAT) AS Score02,
        CAST(FPD AS INT) AS FPD,
        CAST(NUM_CPF AS STRING) AS NUM_CPF
    FROM raw_base_bureau
""")

df_trusted_bureau.createOrReplaceTempView("lake_base_bureau")
#df_trusted_bureau.cache()

#print(log(), "Registros Trusted:", df_trusted_bureau.count())
#df_trusted_bureau.printSchema()
#df_trusted_bureau.show(5, truncate=False)

"""# Salvar na camada Trusted"""

#path_trusted = bucket_trusted_bureau
#print("Trusted path:", path_trusted)

df_trusted_bureau.write \
    .partitionBy("ts_proc_partition","SAFRA") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(bucket_trusted_bureau)

"""# Controle de carga"""

controle_bureau = spark.sql(f"""
    SELECT
        '{output_bureau}' AS name_file,
        ts_proc,
        ts_proc_partition,
        COUNT(*) AS qtd_registros
    FROM lake_base_bureau
    GROUP BY 1,2,3
""")

#controle.createOrReplaceTempView("controle")

#print(log(), "Registros controle:", controle.count())
#controle.show(truncate=False)

"""# Controle de processamento"""
path_control_bureau = os.path.join(bucket_control_bureau, f'tb_controle_processamento_{output_bureau}_{PROCESS_DATE}')
#print("Control path:", path_control_bureau)

controle_bureau.write \
    .mode("append") \
    .option("compression", "snappy") \
    .parquet(path_control_bureau)


# Base telco
bucket_base_telco = "base_telco"
pasta_telco = 'base_telco/'

bucket_raw_telco = f"oci://RAW{namespace}{pasta_telco}"
bucket_trusted_telco = f"oci://TRUSTED{namespace}{pasta_telco}"
bucket_control_telco = f"oci://CONTROL{namespace}{pasta_telco}"
output_telco = f"trusted_{bucket_base_telco}"

"""# Leitura dos dados na camada Raw"""

df_raw_telco = spark.read.parquet(bucket_raw_telco)
df_raw_telco.createOrReplaceTempView("raw_base_telco")

#print(log(), "Registros na Raw:", df_raw_telco.count())
#df_raw_telco.show(5, truncate=False)

"""# Processamento tipagem para camada Trusted"""

df_trusted_telco = spark.sql(f"""
    SELECT
        '{dthproc}' AS ts_proc,
        '{dthproc}' AS ts_proc_partition,
        CAST(NUM_CPF AS STRING) AS NUM_CPF,
        CAST(SAFRA AS INT) AS SAFRA,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 1, 4) AS INT) AS SAFRA_ANO,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 5, 2) AS INT) AS SAFRA_MES,
        CAST(FLAG_INSTALACAO AS BOOLEAN) AS IsSetup,
        CAST(FPD AS BOOLEAN) AS IsFPD,
        CAST(PROD AS STRING) AS ProductDescription,
        CAST(flag_mig2 AS STRING) AS ProductMigration,
        {",".join([f"CAST(var_{i} AS FLOAT) AS Var{i}" for i in range(26,94)])}
    FROM raw_base_telco
""")

df_trusted_telco.createOrReplaceTempView("lake_base_telco")

#print(log(), "Registros Trusted:", df_trusted_telco.count())
#df_trusted_telco.printSchema()
#df_trusted_telco.show(5, truncate=False)

"""# Salvar na camada Trusted"""

bucket_trusted_telco
#print("Trusted path:", bucket_trusted_telco)

df_trusted_telco.write \
    .partitionBy("ts_proc_partition","SAFRA") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(bucket_trusted_telco)

"""# Controle de carga"""

controle_telco = spark.sql(f"""
    SELECT
        '{output_telco}' AS name_file,
        ts_proc,
        ts_proc_partition,
        COUNT(*) AS qtd_registros
    FROM lake_base_telco
    GROUP BY 1,2,3
""")

controle_telco.createOrReplaceTempView("controle_telco")
#controle.cache()

#print(log(), "Registros controle:", controle_telco.count())
#controle_telco.show(truncate=False)

"""# Controle de processamento"""

path_control_telco = os.path.join(bucket_control_telco, f'tb_controle_processamento_{output_telco}_{PROCESS_DATE}')
#print("Control path:", path_control_telco)

controle_telco.write \
    .mode("append") \
    .option("compression", "snappy") \
    .parquet(path_control_telco)


# Base Dados Cadastrais

bucket_cadastro = "base_dados_cadastrais"
pasta_cadastro = 'base_dados_cadastrais/'

bucket_raw_cadastro = f"oci://RAW{namespace}{pasta_cadastro}"
bucket_trusted_cadastro = f"oci://TRUSTED{namespace}{pasta_cadastro}"
bucket_control_cadastro = f"oci://CONTROL{namespace}{pasta_cadastro}"
output_cadastro = f"trusted_{bucket_cadastro}"


"""# Importando os dados"""

df_raw_cadastro = spark.read.parquet(bucket_raw_cadastro)
df_raw_cadastro.createOrReplaceTempView("df_Trusted_base_dados_cadastrais")

#print(log(), "Registros na Raw:", df_raw_cadastro.count())
#df_raw_cadastro.show(5, truncate=False)

"""# Processamento"""

#Alterando o datatype da base
df_base_dados_cadastrais = spark.sql(f"""
    SELECT

        CAST(NUM_CPF AS STRING) AS NUM_CPF,
        '{dthproc}' AS ts_proc,
        '{dthproc}' AS ts_proc_partition,
        CAST(SAFRA AS INT) AS SAFRA,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 1, 4) AS INT) AS SAFRA_ANO,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 5, 2) AS INT) AS SAFRA_MES,

        CAST(FLAG_INSTALACAO AS BOOLEAN) AS FLAG_INSTALACAO,
        CAST(FPD AS BOOLEAN) AS FPD,
        CAST(PROD AS STRING) AS PROD,
        CAST(flag_mig2 AS STRING) AS ProductMigration,
        CAST(STATUSRF AS STRING) AS STATUSRF,
        to_date(DATADENASCIMENTO, 'dd/MM/yyyy') AS DATA_DE_NASCIMENTO,
        to_date(var_12, 'dd/MM/yyyy') AS var_12,

        CAST(var_02 AS INT) AS var_02,
        CAST(var_03 AS INT) AS var_03,
        CAST(var_04 AS INT) AS var_04,
        CAST(var_05 AS INT) AS var_05,
        CAST(var_06 AS INT) AS var_06,
        CAST(var_07 AS FLOAT) AS var_07,
        CAST(var_08 AS INT) AS var_08,
        CAST(var_09 AS INT) AS var_09,
        CAST(var_10 AS STRING) AS Profissao,
        CAST(var_11 AS FLOAT) AS var_11,
        CAST(var_13 AS STRING) AS var_13,
        CAST(var_14 AS INT) AS var_14,
        CAST(var_15 AS STRING) AS Estado,
        CAST(var_16 AS INT) AS var_16,
        CAST(var_17 AS INT) AS var_17,
        CAST(var_18 AS STRING) AS var_18,
        CAST(var_19 AS STRING) AS var_19,
        CAST(var_20 AS STRING) AS var_20,
        CAST(var_21 AS STRING) AS var_21,
        CAST(var_22 AS STRING) AS Cargo,
        CAST(var_23 AS STRING) AS var_23,
        CAST(var_24 AS STRING) AS var_24,
        CAST(var_25 AS STRING) AS Tipo_de_Auxilio,
        CAST(CEP_3_digitos AS STRING) AS CEP_3_digitos
    FROM df_Trusted_base_dados_cadastrais

""")
df_base_dados_cadastrais.createOrReplaceTempView("lake_dados_cadastrais")

#print(log(), "Registros Trusted:", df_base_dados_cadastrais.count())
#df_base_dados_cadastrais.printSchema()
#df_base_dados_cadastrais.show(5, truncate=False)

"""# Salvar na camada Trusted"""

# Salvar tabela no bucket na camada Trusted
#path_trusted = bucket_trusted_cadastro
#print("Trusted path:", path_trusted)

df_base_dados_cadastrais.write \
    .partitionBy("ts_proc_partition","SAFRA") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(bucket_trusted_cadastro)

"""# Controle de carga"""

controle_cadastro = spark.sql(f"""
    SELECT
        '{output_cadastro}' AS name_file,
        ts_proc,
        ts_proc_partition,
        COUNT(*) AS qtd_registros
    FROM lake_dados_cadastrais
    GROUP BY 1,2,3
""")

controle_cadastro.createOrReplaceTempView("controle_cadastro")

#print(log(), "Registros controle:", controle_cadastro.count())
#controle_cadastro.show(truncate=False)

"""# Controle de processamento"""

path_control_cadastro = os.path.join(bucket_control_cadastro, f'tb_controle_processamento_{output_cadastro}_{PROCESS_DATE}')
#print("Control path:", path_control_cadastro)

controle_cadastro.write \
    .mode("append") \
    .option("compression", "snappy") \
    .parquet(path_control_cadastro)

# Base Recarga
bucket_base_recarga = "base_recarga"
pasta_recarga = 'bases_recarga/'

bucket_raw_dim_recarga = f"oci://RAW{namespace}{pasta_recarga}"
bucket_raw_recarga = f"oci://RAW{namespace}{pasta_recarga}BI_FP_ASS_RECARGA_CMV_NOVA/"
bucket_trusted_recarga = f"oci://TRUSTED{namespace}{pasta_recarga}"
bucket_control_recarga = f"oci://CONTROL{namespace}{pasta_recarga}"
output_trusted_recarga = f"trusted_{bucket_base_recarga}"

"""#  Leitura da camada Raw"""

#parquet_files = [path_raw for f in os.listdir(bucket_raw_recarga) if f.endswith('.parquet')]
#df_raw_recarga= spark.read.parquet(*parquet_files, header=True, inferSchema=True)

df_raw_recarga= spark.read.parquet(bucket_raw_recarga)
df_raw_recarga.createOrReplaceTempView("raw_base_recarga")

#print(log(), "Registros na Raw:", df_raw_recarga.count())
#df_raw_recarga.show(5, truncate=False)

"""### Montando as dimensões para enriquecer a base"""

PATH_DIMENSOES_RECARGA = {
    "CANAL_AQUISICAO": f"{bucket_raw_dim_recarga}BI_DIM_CANAL_AQUISICAO_CREDITO.csv",
    "FORMA_PAGAMENTO": f"{bucket_raw_dim_recarga}BI_DIM_FORMA_PAGAMENTO.csv",
    "INSTITUICAO": f"{bucket_raw_dim_recarga}BI_DIM_INSTITUICAO.csv",
    "PLATAFORMA": f"{bucket_raw_dim_recarga}BI_DIM_PLATAFORMA.csv",
    "PROMOCAO": f"{bucket_raw_dim_recarga}BI_DIM_PROMOCAO_CREDITO.csv",
    "STATUS_PLATAFORMA": f"{bucket_raw_dim_recarga}BI_DIM_STATUS_PLATAFORMA.csv",
    "TECNOLOGIA": f"{bucket_raw_dim_recarga}BI_DIM_TECNOLOGIA.csv",
    "TIPO_CREDITO": f"{bucket_raw_dim_recarga}BI_DIM_TIPO_CREDITO.csv",
    "TIPO_INSERCAO": f"{bucket_raw_dim_recarga}BI_DIM_TIPO_INSERCAO.csv",
    "TIPO_RECARGA": f"{bucket_raw_dim_recarga}BI_DIM_TIPO_RECARGA.csv",
}

DIMENSOES_RECARGA = {
    "CANAL_AQUISICAO_CREDITO": "BI_DIM_CANAL_AQUISICAO_CREDITO.csv",
    "FORMA_PAGAMENTO": "BI_DIM_FORMA_PAGAMENTO.csv",
    "INSTITUICAO": "BI_DIM_INSTITUICAO.csv",
    "PLANO_PRECO": "BI_DIM_PLANO_PRECO.csv",
    "PLATAFORMA": "BI_DIM_PLATAFORMA.csv",
    "PROMOCAO_CREDITO": "BI_DIM_PROMOCAO_CREDITO.csv",
    "STATUS_PLATAFORMA": "BI_DIM_STATUS_PLATAFORMA.csv",
    "TECNOLOGIA": "BI_DIM_TECNOLOGIA.csv",
    "TIPO_CREDITO": "BI_DIM_TIPO_CREDITO.csv",
    "TIPO_INSERCAO": "BI_DIM_TIPO_INSERCAO.csv",
    "TIPO_RECARGA": "BI_DIM_TIPO_RECARGA.csv",
}


dfs_dim_recarga = {}

for nome_dim, arquivo in DIMENSOES_RECARGA.items():
    path = f"{bucket_raw_dim_recarga}/{arquivo}"

    dfs_dim_recarga[nome_dim] = (
        spark.read
        .option("header", True)
        .option("sep", ",")
        .option("inferSchema", True)
        .csv(path)
        
        #spark.read.csv(path, header=True, sep=",", inferSchema=True)
    )

df_CANAL_AQUISICAO_CREDITO = dfs_dim_recarga["CANAL_AQUISICAO_CREDITO"]
df_FORMA_PAGAMENTO        = dfs_dim_recarga["FORMA_PAGAMENTO"]
df_INSTITUICAO            = dfs_dim_recarga["INSTITUICAO"]
df_PLANO_PRECO            = dfs_dim_recarga["PLANO_PRECO"]
df_PLATAFORMA             = dfs_dim_recarga["PLATAFORMA"]
df_PROMOCAO_CREDITO       = dfs_dim_recarga["PROMOCAO_CREDITO"]
df_STATUS_PLATAFORMA      = dfs_dim_recarga["STATUS_PLATAFORMA"]
df_TECNOLOGIA              = dfs_dim_recarga["TECNOLOGIA"]
df_TIPO_CREDITO           = dfs_dim_recarga["TIPO_CREDITO"]
df_TIPO_INSERCAO          = dfs_dim_recarga["TIPO_INSERCAO"]
df_TIPO_RECARGA           = dfs_dim_recarga["TIPO_RECARGA"]


"""# Processamento tipagem para camada Trusted"""

df_base_recarga = spark.sql(f"""
    SELECT
        '{dthproc}' AS ts_proc,
        '{dthproc}' AS ts_proc_partition,
        CAST(NUM_CPF AS STRING) AS NUM_CPF,
        CAST(DW_NUM_NTC AS STRING) AS DW_NUM_NTC,
        CAST(DW_NUM_CLIENTE AS STRING) AS DW_NUM_CLIENTE,
        CAST(DAT_INSERCAO_CREDITO AS STRING) AS DAT_INSERCAO_CREDITO,
        CAST(HOR_INSERCAO_CREDITO AS STRING) AS HOR_INSERCAO_CREDITO,
        CAST(COD_TECNOLOGIA_DW AS STRING) AS COD_TECNOLOGIA_DW,
        CAST(COD_CANAL_AQUISICAO AS INT) AS COD_CANAL_AQUISICAO,
        CAST(COD_TIPO_CREDITO AS STRING) AS COD_TIPO_CREDITO,
        CAST(COD_PROMOCAO AS INT) AS COD_PROMOCAO,
        CAST(VAL_CREDITO_INSERIDO AS FLOAT) AS VAL_CREDITO_INSERIDO,
        CAST(VAL_BONUS AS FLOAT) AS VAL_BONUS,
        CAST(VAL_REAL AS FLOAT) AS VAL_REAL,
        CAST(COD_PLATAFORMA_ATU AS STRING) AS COD_PLATAFORMA_ATU,
        CAST(COD_STATUS_PLATAFORMA AS STRING) AS COD_STATUS_PLATAFORMA,
        CAST(IND_METODO_PAGAMENTO AS STRING) AS IND_METODO_PAGAMENTO,
        CAST(DW_PLANO_TARIFACAO AS INT) AS DW_PLANO_TARIFACAO,
        CAST(DW_TIPO_RECARGA AS INT) AS DW_TIPO_RECARGA,
        CAST(DW_TIPO_INSERCAO AS INT) AS DW_TIPO_INSERCAO,
        CAST(DW_FORMA_PAGAMENTO AS INT) AS DW_FORMA_PAGAMENTO,
        CAST(DW_INSTITUICAO AS INT) AS DW_INSTITUICAO,
        CAST(COD_GRUPO_CARTAO AS STRING) AS COD_GRUPO_CARTAO,
        CAST(DSC_GRUPO_CARTAO_WPP AS STRING) AS DSC_GRUPO_CARTAO_WPP,
        CAST(FLAG_SOS AS INT) AS FLAG_SOS,
        CAST(VALOR_SOS AS INT) AS VALOR_SOS
    FROM raw_base_recarga
""")

df_base_recarga.createOrReplaceTempView("df_base_recarga")

#total_recarga = df_base_recarga.count()
#print(log(), "Registros Base:",total_recarga)
#df_base_recarga.printSchema()
#df_base_recarga.show(5, truncate=False)

"""#Inserindo os dados das dimensões"""
#DIM CANAL_AQUISICAO_CREDITO
df_CANAL_AQUISICAO_CREDITO.createOrReplaceTempView("CANAL_AQUISICAO_CREDITO")
df_base_recarga_canal = spark.sql("""
    SELECT
        f.*,
        c.COD_CANAL_AQUISICAO AS CAN_COD_CANAL_AQUISICAO,
        c.DSC_CANAL_AQUISICAO AS CAN_DSC_CANAL_AQUISICAO,
        c.COD_SISTEMA_DW AS CAN_COD_SISTEMA_DW,
        c.DAT_ATUALIZACAO_DW AS CAN_DAT_ATUALIZACAO_DW,
        c.DAT_CRIACAO_DW AS CAN_DAT_CRIACAO_DW,
        c.COD_CANAL_AQUISICAO_BI AS CAN_COD_CANAL_AQUISICAO_BI,
        c.DSC_CANAL_AQUISICAO_BI AS CAN_DSC_CANAL_AQUISICAO_BI,
        c.COD_AGENTE_CREDITO AS CAN_COD_AGENTE_CREDITO,
        c.DAT_EXPIRACAO_DW AS CAN_DAT_EXPIRACAO_DW,
        c.COD_TIPO_CREDITO AS CAN_COD_TIPO_CREDITO,
        c.COD_TIPO_INSTITUICAO AS CAN_COD_TIPO_INSTITUICAO,
        c.DSC_TIPO_INSTITUICAO AS CAN_DSC_TIPO_INSTITUICAO
    FROM df_base_recarga f
    LEFT JOIN CANAL_AQUISICAO_CREDITO c
        ON f.COD_CANAL_AQUISICAO = c.COD_CANAL_AQUISICAO
""")

df_base_recarga_canal.createOrReplaceTempView("df_base_recarga_canal")
#total_linhas = df_base_recarga_canal.count()
#if (total_linhas == total_recarga):  #df_base_recarga_canal.count() == df_base_recarga.count()
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_canal.show(5)

#DIM FORMA_PAGAMENTO
df_FORMA_PAGAMENTO.createOrReplaceTempView("FORMA_PAGAMENTO")
df_base_recarga_forma = spark.sql("""
    SELECT
        f.*,
        fp.COD_FORMA_PAGAMENTO AS FP_COD_FORMA_PAGAMENTO,
        fp.DSC_FORMA_PAGAMENTO AS FP_DSC_FORMA_PAGAMENTO,
        fp.DAT_CRIACAO_DW AS FP_DAT_CRIACAO_DW,
        fp.DAT_EXPIRACAO_DW AS FP_DAT_EXPIRACAO_DW
    FROM df_base_recarga_canal f
    LEFT JOIN FORMA_PAGAMENTO fp
        ON f.DW_FORMA_PAGAMENTO = fp.DW_FORMA_PAGAMENTO
""")

df_base_recarga_forma.createOrReplaceTempView("df_base_recarga_forma")
#total_linhas= df_base_recarga_forma.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_forma.show(5)

#DIM INSTITUICAO
df_INSTITUICAO.createOrReplaceTempView("INSTITUICAO")
df_base_recarga_instituicao = spark.sql("""
    SELECT
        f.*,
        i.COD_INSTITUICAO AS INS_COD_INSTITUICAO,
        i.DSC_INSTITUICAO AS INS_DSC_INSTITUICAO,
        i.COD_TIPO_INSTITUICAO AS INS_COD_TIPO_INSTITUICAO,
        i.DSC_TIPO_INSTITUICAO AS INS_DSC_TIPO_INSTITUICAO,
        i.COD_SISTEMA_DW AS INS_COD_SISTEMA_DW,
        i.DAT_EXPIRACAO_DW AS INS_DAT_EXPIRACAO_DW,
        i.DAT_CRIACAO_DW AS INS_DAT_CRIACAO_DW,
        i.COD_AGENTE AS INS_COD_AGENTE
    FROM df_base_recarga_forma f
    LEFT JOIN INSTITUICAO i
        ON f.DW_INSTITUICAO = i.DW_INSTITUICAO
""")

df_base_recarga_instituicao.createOrReplaceTempView("df_base_recarga_instituicao")
#total_linhas = df_base_recarga_instituicao.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_instituicao.show(5)

#DIM PLANO_PRECO
df_PLANO_PRECO.createOrReplaceTempView("PLANO_PRECO")
df_base_recarga_plano = spark.sql("""
    SELECT
        f.*,
        pp.DW_PLANO AS PP_DW_PLANO,
        pp.COD_PLANO_PRECO AS PP_COD_PLANO_PRECO,
        pp.DSC_PLANO_PRECO AS PP_DSC_PLANO_PRECO,
        pp.COD_TIPO_CLIENTE AS PP_COD_TIPO_CLIENTE,
        pp.COD_SUB_TIPO_CLIENTE AS PP_COD_SUB_TIPO_CLIENTE,
        pp.DW_TIPO_CLIENTE AS PP_DW_TIPO_CLIENTE,
        pp.DAT_EFETIVACAO AS PP_DAT_EFETIVACAO,
        pp.DAT_EXPIRACAO AS PP_DAT_EXPIRACAO,
        pp.DSC_PLANO_PRECO_BI AS PP_DSC_PLANO_PRECO_BI,
        pp.DSC_GRUPO_PLANO_BI AS PP_DSC_GRUPO_PLANO_BI,
        pp.DSC_TIPO_PLANO_BI AS PP_DSC_TIPO_PLANO_BI,
        pp.IND_AMDOCS_PLAT_PRE AS PP_IND_AMDOCS_PLAT_PRE,
        pp.COD_TRATAMENTO_ESPECIAL AS PP_COD_TRATAMENTO_ESPECIAL,
        pp.COD_SISTEMA_DW AS PP_COD_SISTEMA_DW,
        pp.COD_TECNOLOGIA_DW AS PP_COD_TECNOLOGIA_DW,
        pp.DAT_EXPIRACAO_DW AS PP_DAT_EXPIRACAO_DW,
        pp.DAT_ATUALIZACAO_DW AS PP_DAT_ATUALIZACAO_DW,
        pp.DAT_CRIACAO_DW AS PP_DAT_CRIACAO_DW,
        pp.NUM_FRANQUIA_MINUTOS_BI AS PP_NUM_FRANQUIA_MINUTOS_BI,
        pp.NUM_FRANQUIA_REAIS_BI AS PP_NUM_FRANQUIA_REAIS_BI,
        pp.NUM_FRANQUIA_EVENTOS_BI AS PP_NUM_FRANQUIA_EVENTOS_BI,
        pp.NUM_FRANQUIA_VOLUME_BI AS PP_NUM_FRANQUIA_VOLUME_BI,
        pp.COD_PLANO_COMPONENTE AS PP_COD_PLANO_COMPONENTE,
        pp.DSC_PLANO_PRECO_UNICO_BI AS PP_DSC_PLANO_PRECO_UNICO_BI,
        pp.DSC_MODALIDADE_PLANO AS PP_DSC_MODALIDADE_PLANO
    FROM df_base_recarga_instituicao f
    LEFT JOIN PLANO_PRECO pp
        ON CAST(f.DW_PLANO_TARIFACAO AS STRING) = CAST(pp.COD_PLANO_PRECO AS STRING)
""")

df_base_recarga_plano.createOrReplaceTempView("df_base_recarga_plano")
#total_linhas = df_base_recarga_plano.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_plano.show(5)

#DIM STATUS_PLATAFORMA
df_STATUS_PLATAFORMA.createOrReplaceTempView("STATUS_PLATAFORMA")
df_base_plataforma = spark.sql("""
    SELECT
        f.*,
        sp.DSC_STATUS_PLATAFORMA AS SP_DSC_STATUS_PLATAFORMA,
        sp.IND_ATIVO AS SP_IND_ATIVO,
        sp.DAT_ATUALIZACAO_DW AS SP_DAT_ATUALIZACAO_DW,
        sp.DAT_CRIACAO_DW AS SP_DAT_CRIACAO_DW,
        sp.COD_STATUS_PLAT_GRP AS SP_COD_STATUS_PLAT_GRP,
        sp.IND_STS_PLAT_GRP_ATIVO AS SP_IND_STS_PLAT_GRP_ATIVO
    FROM df_base_recarga_plano f
    LEFT JOIN STATUS_PLATAFORMA sp
        ON f.COD_STATUS_PLATAFORMA = sp.COD_STATUS_PLATAFORMA
""")

df_base_plataforma.createOrReplaceTempView("df_base_plataforma")
#total_linhas = df_base_plataforma.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_plataforma.show(5)

#DIM PROMOCAO
df_PROMOCAO_CREDITO.createOrReplaceTempView("PROMOCAO_CREDITO")
df_base_recarga_promocao = spark.sql("""
    SELECT
        f.*,
        pr.DSC_PROMOCAO AS PR_DSC_PROMOCAO,
        pr.DAT_EXPIRACAO_DW AS PR_DAT_EXPIRACAO_DW,
        pr.DAT_ATUALIZACAO_DW AS PR_DAT_ATUALIZACAO_DW,
        pr.DAT_CRIACAO_DW AS PR_DAT_CRIACAO_DW,
        pr.COD_PROM_GRUPO_CARTAO AS PR_COD_PROM_GRUPO_CARTAO,
        pr.DSC_NOME_PROMOCAO AS PR_DSC_NOME_PROMOCAO,
        pr.COD_TIPO_PROMOCAO AS PR_COD_TIPO_PROMOCAO,
        pr.DAT_INICIO_VIGENCIA AS PR_DAT_INICIO_VIGENCIA,
        pr.DAT_FIM_VIGENCIA AS PR_DAT_FIM_VIGENCIA,
        pr.VAL_PROMOCAO AS PR_VAL_PROMOCAO,
        pr.NUM_CONTA_DEDICADA AS PR_NUM_CONTA_DEDICADA
    FROM df_base_plataforma f
    LEFT JOIN PROMOCAO_CREDITO pr
        ON f.COD_PROMOCAO = pr.COD_PROMOCAO
""")

df_base_recarga_promocao.createOrReplaceTempView("df_base_recarga_promocao")
#total_linhas = df_base_recarga_promocao.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_promocao.show(5)

#DIM TECNOLOGIA
df_TECNOLOGIA.createOrReplaceTempView("TECNOLOGIA")
df_base_recarga_tecnologia = spark.sql("""
    SELECT
        f.*,
        t.DSC_TECNOLOGIA AS TEC_DSC_TECNOLOGIA,
        t.DAT_ATUALIZACAO_DW AS TEC_DAT_ATUALIZACAO_DW,
        t.DAT_CRIACAO_DW AS TEC_DAT_CRIACAO_DW,
        t.COD_TECNOLOGIA_SVA AS TEC_COD_TECNOLOGIA_SVA
    FROM df_base_recarga_promocao f
    LEFT JOIN TECNOLOGIA t
        ON CAST(f.COD_TECNOLOGIA_DW AS STRING) = CAST(t.COD_TECNOLOGIA_DW AS STRING)
""")

df_base_recarga_tecnologia.createOrReplaceTempView("df_base_recarga_tecnologia")
#total_linhas = df_base_recarga_tecnologia.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_tecnologia.show(5)

#DIM TIPO_CREDITO
df_TIPO_CREDITO.createOrReplaceTempView("TIPO_CREDITO")
# Perform the join using the renamed fact column
df_base_recarga_tipocredito = spark.sql("""
    SELECT
        f.*,
        tc.COD_TIPO_CREDITO AS TPC_COD_TIPO_CREDITO,
        tc.DSC_TIPO_CREDITO AS TPC_DSC_TIPO_CREDITO,
        tc.DAT_EXPIRACAO_DW AS TPC_DAT_EXPIRACAO_DW,
        tc.DAT_ATUALIZACAO_DW AS TPC_DAT_ATUALIZACAO_DW,
        tc.DAT_CRIACAO_DW AS TPC_DAT_CRIACAO_DW
    FROM df_base_recarga_tecnologia f
    LEFT JOIN TIPO_CREDITO tc
        ON f.COD_TIPO_CREDITO = tc.COD_TIPO_CREDITO
""")

df_base_recarga_tipocredito.createOrReplaceTempView("df_base_recarga_tipocredito")
#total_linhas = df_base_recarga_tipocredito.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_tipocredito.show(5)

#DIM TIPO_INSERCAO
df_TIPO_INSERCAO.createOrReplaceTempView("TIPO_INSERCAO")
df_base_recarga_tipoinsercao = spark.sql("""
       SELECT
        f.*,
        -- colunas da dimensão TIPO_INSERCAO com prefixo TPI_
        ti.DW_TIPO_INSERCAO  AS TPI_DW_TIPO_INSERCAO,
        ti.DSC_TIPO_INSERCAO AS TPI_DSC_TIPO_INSERCAO,
        ti.DAT_EXPIRACAO_DW  AS TPI_DAT_EXPIRACAO_DW,
        ti.DAT_CRIACAO_DW    AS TPI_DAT_CRIACAO_DW
    FROM df_base_recarga_tipocredito f
    LEFT JOIN TIPO_INSERCAO ti
        ON f.DW_TIPO_INSERCAO = ti.DW_TIPO_INSERCAO
""")

df_base_recarga_tipoinsercao.createOrReplaceTempView("df_base_recarga_tipoinsercao")
#total_linhas = df_base_recarga_tipoinsercao.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_base_recarga_tipoinsercao.show(5)

#DIM TIPO_RECARGA
df_TIPO_RECARGA.createOrReplaceTempView("TIPO_RECARGA")
df_bases_recarga_tiporecarga = spark.sql("""
       SELECT
        f.*,
        -- colunas da dimensão TIPO_RECARGA com prefixo TR_
        tr.DW_TIPO_RECARGA  AS TR_DW_TIPO_RECARGA,
        tr.DSC_TIPO_RECARGA AS TR_DSC_TIPO_RECARGA,
        tr.DAT_EXPIRACAO_DW AS TR_DAT_EXPIRACAO_DW,
        tr.DAT_CRIACAO_DW   AS TR_DAT_CRIACAO_DW
    FROM df_base_recarga_tipoinsercao f
    LEFT JOIN TIPO_RECARGA tr
        ON f.DW_TIPO_RECARGA = tr.DW_TIPO_RECARGA
""")

df_bases_recarga_tiporecarga.createOrReplaceTempView("df_bases_recarga_tiporecarga")
#total_linhas = df_bases_recarga_tiporecarga.count()

#if (total_linhas == total_recarga):
#    print(log(), "Join valido Registros Base:", total_linhas)
#    df_bases_recarga_tiporecarga.show(5)

# criando coluna SAFRA
df_bases_recarga = spark.sql("""
SELECT
    trunc(to_timestamp(f.DAT_INSERCAO_CREDITO, 'ddMMMyyyy:HH:mm:ss'),'MM') AS SAFRA,
    f.*
FROM df_bases_recarga_tiporecarga f
""")
#df_bases_recarga.show(6)

df_bases_recarga.createOrReplaceTempView("df_bases_recarga")

"""# Salvar na camada Trusted"""
#print("Trusted path:", bucket_trusted_recarga)

df_bases_recarga.write \
    .partitionBy("ts_proc_partition","SAFRA") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(bucket_trusted_recarga)

"""# Controle de carga"""
df_controle_recarga = spark.sql (f"""
SELECT
    '{output_trusted_recarga}' AS name_file,
    ts_proc,
    ts_proc_partition,
    count(*) as qtd_registros
from df_bases_recarga
    GROUP BY 1,2,3
""")

#df_controle.show()

"""# Controle de processamento"""
path_control_recarga = os.path.join(bucket_control_recarga, f'tb_controle_processamento_{output_trusted_recarga}_{PROCESS_DATE}')
#print("Control path:", path_control_recarga)

df_controle_recarga.write \
  .mode('append') \
  .option('compression', 'snappy') \
  .parquet(path_control_recarga)
  
# Base Pagamento

bucket_base_pagamento = "base_pagamento"
pasta_pagamento = 'book_pagamento/dados_pagamento/'

bucket_raw_pagamento = f"oci://RAW{namespace}{pasta_pagamento}"
bucket_trusted_pagamento = f"oci://TRUSTED{namespace}{pasta_pagamento}"
bucket_control_pagamento = f"oci://CONTROL{namespace}{pasta_pagamento}"
output_trusted_pagamento = f"trusted_{bucket_base_pagamento}"



"""# Leitura dos dados na camada Raw"""

#parquet_files = [path_raw for f in os.listdir(bucket_raw_pagamento) if f.endswith('.parquet')]
#df_raw_pagamento= spark.read.parquet(*parquet_files, header=True, inferSchema=True)

#bucket_raw_pagamento = "oci://RAW@grxzqsiaote6/book_pagamento/dados_pagamento/"

df_raw_pagamento = spark.read.parquet(bucket_raw_pagamento)
df_raw_pagamento.createOrReplaceTempView("raw_base_pagamento")

#print(log(), "Registros na Raw:", df_raw_pagamento.count())
#df_raw_pagamento.show(5, truncate=False)

"""# Processamento tipagem para camada Trusted"""

df_trusted_pagamento = spark.sql(f"""
SELECT
'{dthproc}' AS ts_proc,
'{dthproc}' AS ts_proc_partition,
CAST(NUM_CPF AS STRING) AS NUM_CPF,
TO_DATE(DAT_STATUS_FATURA, 'ddMMMyyyy:HH:mm:ss') AS DAT_STATUS_FATURA,
CAST(CONTRATO AS STRING) AS CONTRATO,
CAST(SEQ_FATURA AS INT) AS SEQ_FATURA,
CAST(NUM_SUB_SEQ_FATURA AS INT) AS NUM_SUB_SEQ_FATURA,
CAST(NUM_CREDITO_SEQ AS INT) AS NUM_CREDITO_SEQ,
CAST(DW_TIPO_FATURA AS INT) AS DW_TIPO_FATURA,
CAST(IND_STATUS_FATURA AS STRING) AS IND_STATUS_FATURA,
CAST(DW_NUM_CLIENTE AS STRING) AS DW_NUM_CLIENTE,
CAST(DW_AREA AS INT) AS DW_AREA,
CAST(DW_UN_NEGOCIO AS INT) AS DW_UN_NEGOCIO,
CAST(DW_FORMA_PAGAMENTO AS INT) AS DW_FORMA_PAGAMENTO,
CAST(VAL_PAGAMENTO_FATURA AS FLOAT) AS VAL_PAGAMENTO_FATURA,
to_date(to_timestamp(DAT_CRIACAO_DW, 'ddMMMyyyy:HH:mm:ss')) AS DAT_CRIACAO_DW,
date_format(to_timestamp(DAT_CRIACAO_DW, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_CRIACAO_DW,
CAST(DW_BANCO AS STRING) AS DW_BANCO,
CAST(DW_TIPO_PAGAMENTO AS STRING) AS DW_TIPO_PAGAMENTO,
CAST(NUM_BANCO_PAGAMENTO AS STRING) AS NUM_BANCO_PAGAMENTO,
CAST(NUM_AGENCIA_PAGAMENTO AS STRING) AS NUM_AGENCIA_PAGAMENTO,
CAST(NUM_CC_PAGAMENTO AS STRING) AS NUM_CC_PAGAMENTO,
CAST(DW_MOTIVO_ESTORNO AS STRING) AS DW_MOTIVO_ESTORNO,
CAST(VAL_DESCONTO_ITEM AS FLOAT) AS VAL_DESCONTO_ITEM,
CAST(VAL_PAGAMENTO_ITEM AS FLOAT) AS VAL_PAGAMENTO_ITEM,
CAST(VAL_JUROS_MULTAS_ITEM AS FLOAT) AS VAL_JUROS_MULTAS_ITEM,
CAST(VAL_MULTA_EQUIP_ITEM AS FLOAT) AS VAL_MULTA_EQUIP_ITEM,
CAST(VAL_MULTA_EQUIP_TOTAL AS FLOAT) AS VAL_MULTA_EQUIP_TOTAL,
CAST(VAL_MULTA_FID_ITEM AS FLOAT) AS VAL_MULTA_FID_ITEM,
CAST(COD_ORIGEM_NETUNO AS STRING) AS COD_ORIGEM_NETUNO,
CAST(COD_CONTA_ATIVIDADE AS STRING) AS COD_CONTA_ATIVIDADE,
CAST(SEQ_ENTIDADE_ATIVIDADE AS INT) AS SEQ_ENTIDADE_ATIVIDADE,
to_date(to_timestamp(DAT_CRIACAO_ATIVIDADE, 'ddMMMyyyy:HH:mm:ss')) AS DAT_CRIACAO_ATIVIDADE,
date_format(to_timestamp(DAT_CRIACAO_ATIVIDADE, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_CRIACAO_ATIVIDADE,
to_date(to_timestamp(DAT_ATUALIZACAO_ATIVIDADE, 'ddMMMyyyy:HH:mm:ss')) AS DAT_ATUALIZACAO_ATIVIDADE,
date_format(to_timestamp(DAT_ATUALIZACAO_ATIVIDADE, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_ATUALIZACAO_ATIVIDADE,
CAST(COD_LOGIN_OPERADOR_ATIVIDADE AS STRING) AS COD_LOGIN_OPERADOR_ATIVIDADE,
CAST(COD_ATIVIDADE AS STRING) AS COD_ATIVIDADE,
CAST(COD_RAZAO_ATIVIDADE AS STRING) AS COD_RAZAO_ATIVIDADE,
TO_DATE(DAT_BAIXA_ATIVIDADE, 'ddMMMyyyy:HH:mm:ss') AS DAT_BAIXA_ATIVIDADE,
CAST(VAL_BAIXA_ATIVIDADE AS FLOAT) AS VAL_BAIXA_ATIVIDADE,
TO_DATE(DAT_DEPOSITO_ATIVIDADE, 'ddMMMyyyy:HH:mm:ss') AS DAT_DEPOSITO_ATIVIDADE,
CAST(COD_FUNDO_ATIVIDADE AS STRING) AS COD_FUNDO_ATIVIDADE,
CAST(COD_BANCO_ATIVIDADE AS STRING) AS COD_BANCO_ATIVIDADE,
CAST(NUM_CONTA_ATIVIDADE AS STRING) AS NUM_CONTA_ATIVIDADE,
CAST(COD_AGENCIA_ATIVIDADE AS STRING) AS COD_AGENCIA_ATIVIDADE,
CAST(SEQ_ENTIDADE_PAGAMENTO AS INT) AS SEQ_ENTIDADE_PAGAMENTO,
to_date(to_timestamp(DAT_CRIACAO_PAGAMENTO, 'ddMMMyyyy:HH:mm:ss')) AS DAT_CRIACAO_PAGAMENTO,
date_format(to_timestamp(DAT_CRIACAO_PAGAMENTO, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_CRIACAO_PAGAMENTO,
to_date(to_timestamp(DAT_ATUALIZACAO_PAGAMENTO, 'ddMMMyyyy:HH:mm:ss')) AS DAT_ATUALIZACAO_PAGAMENTO,
date_format(to_timestamp(DAT_ATUALIZACAO_PAGAMENTO, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_ATUALIZACAO_PAGAMENTO,
CAST(COD_LOGIN_PAGAMENTO AS STRING) AS COD_LOGIN_PAGAMENTO,
CAST(COD_FORMA_PAGAMENTO AS STRING) AS COD_FORMA_PAGAMENTO,
CAST(VAL_ORIGINAL_PAGAMENTO AS FLOAT) AS VAL_ORIGINAL_PAGAMENTO,
CAST(NUM_FATURA_PAGAMENTO AS STRING) AS NUM_FATURA_PAGAMENTO,
CAST(COD_TIPO_PAGAMENTO AS STRING) AS COD_TIPO_PAGAMENTO,
CAST(DSC_NOME_BANCO_PAGAMENTO AS STRING) AS DSC_NOME_BANCO_PAGAMENTO,
CAST(SEQ_ARQUIVO_PAGAMENTO AS INT) AS SEQ_ARQUIVO_PAGAMENTO,
CAST(NUM_PARCELA_PAGAMENTO AS INT) AS NUM_PARCELA_PAGAMENTO,
CAST(NUM_AGRUPADOR_PAGAMENTO AS INT) AS NUM_AGRUPADOR_PAGAMENTO,
CAST(DSC_PAGAMENTO AS STRING) AS DSC_PAGAMENTO,
CAST(VAL_ATUAL_PAGAMENTO AS FLOAT) AS VAL_ATUAL_PAGAMENTO,
CAST(COD_METODO_PAGAMENTO AS INT) AS COD_METODO_PAGAMENTO,
CAST(IND_STATUS_PAGAMENTO AS STRING) AS IND_STATUS_PAGAMENTO,
TO_DATE(DAT_STATUS_PAGAMENTO, 'ddMMMyyyy:HH:mm:ss') AS DAT_STATUS_PAGAMENTO,
CAST(COD_ARQUIVO_PAGAMENTO AS STRING) AS COD_ARQUIVO_PAGAMENTO,
CAST(COD_NETUNO_PAGAMENTO AS STRING) AS COD_NETUNO_PAGAMENTO,
to_date(to_timestamp(DAT_CRIACAO_CREDITO, 'ddMMMyyyy:HH:mm:ss')) AS DAT_CRIACAO_CREDITO,
date_format(to_timestamp(DAT_CRIACAO_CREDITO, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_CRIACAO_CREDITO,
TO_DATE(DAT_ATUALIZACAO_CREDITO, 'ddMMMyyyy:HH:mm:ss')                      AS DAT_ATUALIZACAO_CREDITO,
CAST(COD_LOGIN_CREDITO AS STRING) AS COD_LOGIN_CREDITO,
CAST(VAL_PAGAMENTO_CREDITO AS FLOAT) AS VAL_PAGAMENTO_CREDITO,
CAST(IND_TIPO_CREDITO AS STRING) AS IND_TIPO_CREDITO,
CAST(SEQ_PAGAMENTO_CREDITO AS INT) AS SEQ_PAGAMENTO_CREDITO,
CAST(SEQ_FATURA_CREDITO AS INT) AS SEQ_FATURA_CREDITO,
CAST(COD_ALOCACAO_CREDITO AS STRING) AS COD_ALOCACAO_CREDITO,
CAST(COD_DESALOCACAO_CREDITO AS STRING) AS COD_DESALOCACAO_CREDITO,
CAST(SEQ_ENTIDADE_CREDITO AS INT) AS SEQ_ENTIDADE_CREDITO,
CAST(COD_TIPO_FATURA AS STRING) AS COD_TIPO_FATURA,
TO_DATE(DAT_ATIVIDADE_CREDITO, 'ddMMMyyyy:HH:mm:ss') AS DAT_ATIVIDADE_CREDITO,
TO_DATE(DAT_VENCIMENTO_CREDITO, 'ddMMMyyyy:HH:mm:ss') AS DAT_VENCIMENTO_CREDITO
FROM raw_base_pagamento
""")

df_trusted_pagamento.createOrReplaceTempView("lake_base_pagamento")

#print(log(), "Registros Trusted:", df_trusted_pagamento.count())
#df_trusted_pagamento.#printSchema()
#df_trusted_pagamento.show(5, truncate=False)

"""# Salvar na camada Trusted"""
df_trusted_pagamento.write \
    .partitionBy("ts_proc_partition") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(bucket_trusted_pagamento)

"""# Controle de carga"""

controle_pagamento = spark.sql (f"""
    SELECT
        '{output_trusted_pagamento}' AS name_file,
        ts_proc,
        ts_proc_partition,
        count(*) as qtd_registros
    from lake_base_pagamento
    GROUP BY 1,2,3
""")

controle_pagamento.createOrReplaceTempView("controle")

#print(log(), "Registros controle:", controle_pagamento.count())
#controle_pagamento.show(truncate=False)

"""# Controle de processamento"""

path_control_pagamento = os.path.join(bucket_control_pagamento, f'tb_controle_processamento_{output_trusted_pagamento}_{PROCESS_DATE}')
#print("Control path:", path_control_pagamento)

controle_pagamento.write \
  .mode('append') \
  .option('compression', 'snappy') \
  .parquet(path_control_pagamento)
  
# Base atraso

bucket_base_atraso = "base_atraso"
pasta_atraso = 'book_atraso/'

bucket_raw_dim_atraso = f"oci://RAW{namespace}{pasta_atraso}BI_DIM_TIPO_FATURAMENTO.csv"
bucket_raw_atraso = f"oci://RAW{namespace}{pasta_atraso}dados_faturamento/"
bucket_trusted_atraso = f"oci://TRUSTED{namespace}{pasta_atraso}"
bucket_control_atraso = f"oci://CONTROL{namespace}{pasta_atraso}"
output_trusted_atraso = f"trusted_{bucket_base_atraso}"

"""#  Leitura da camada Raw"""

df_raw_atraso = spark.read.parquet(bucket_raw_atraso)
df_raw_atraso.createOrReplaceTempView("raw_base_atraso")

#print(log(), "Registros na Raw:", df_raw_atraso.count())
#df_raw_atraso.show(5, truncate=False)
#df_raw_atraso.printSchema()

#csv_files = [bucket_raw_atraso for f in os.listdir(bucket_raw) if f.endswith('.csv')]
#df_dim_atraso = spark.read.csv(*csv_files, header=True, inferSchema=True, sep=',')

csv_files = bucket_raw_dim_atraso
df_dim_atraso = spark.read.csv(csv_files, header=True, inferSchema=True, sep=',')
df_dim_atraso.createOrReplaceTempView("df_tipo_faturamento")

#print(log(), "Registros na Raw:", df_dim_atraso.count())
#df_dim_atraso.show(5, truncate=False)

#print(log(), "Registros na Raw:", df_raw_atraso.count())
#df_raw_atraso.show(5, truncate=False)

"""# Processamento tipagem para camada Trusted"""

df_trusted_atraso = spark.sql(f"""
SELECT
    '{dthproc}' AS ts_proc,
    '{dthproc}' AS ts_proc_partition,
    CAST(NUM_CPF AS STRING)                                     AS NUM_CPF,
    TO_DATE(DAT_REFERENCIA, 'ddMMMyyyy:HH:mm:ss')               AS DAT_REFERENCIA,
    CAST(NUM_FATURA_HASH AS STRING)                              AS NUM_FATURA_HASH,
    CAST(NUM_ENT_SEQ_FATURA AS INT)                              AS NUM_ENT_SEQ_FATURA,
    CAST(CONTRATO AS BIGINT)                                     AS CONTRATO,
    CAST(DW_UN_NEGOCIO AS INT)                                   AS DW_UN_NEGOCIO,
    CAST(DW_HIS_PONTO_VENDA_COMTA AS BIGINT)                     AS DW_HIS_PONTO_VENDA_COMTA,
    CAST(DW_NUM_CLIENTE AS BIGINT)                               AS DW_NUM_CLIENTE,
    CAST(DW_AREA AS INT)                                         AS DW_AREA,
    CAST(DW_CICLO AS INT)                                        AS DW_CICLO,
    CAST(DW_TIPO_CLIENTE_CONTA AS INT)                           AS DW_TIPO_CLIENTE_CONTA,
    CAST(DW_OFERTA AS INT)                                       AS DW_OFERTA,
    CAST(DW_FAIXA_AGING_FATURA AS INT)                           AS DW_FAIXA_AGING_FATURA,
    CAST(DW_FAIXA_AGING_DIVIDA AS INT)                           AS DW_FAIXA_AGING_DIVIDA,
    CAST(DW_FAIXA_TEMPO_BASE AS INT)                             AS DW_FAIXA_TEMPO_BASE,
    CAST(DW_FAIXA_AGING_PROX_FECH AS INT)                        AS DW_FAIXA_AGING_PROX_FECH,
    CAST(DW_TIPO_FATURAMENTO AS INT)                             AS DW_TIPO_FATURAMENTO,
    CAST(COD_PLATAFORMA AS STRING)                               AS COD_PLATAFORMA,

    to_date(to_timestamp(DAT_CRIACAO_REGISTRO_TRANS, 'ddMMMyyyy:HH:mm:ss')) AS DAT_CRIACAO_REGISTRO_TRANS,
    date_format(to_timestamp(DAT_CRIACAO_REGISTRO_TRANS, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_CRIACAO_REGISTRO_TRANS,
    to_date(to_timestamp(DAT_ALTERACAO_REGISTRO_TRANS, 'ddMMMyyyy:HH:mm:ss')) AS DAT_ALTERACAO_REGISTRO_TRANS,
    date_format(to_timestamp(DAT_ALTERACAO_REGISTRO_TRANS, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_ALTERACAO_REGISTRO_TRANS,
    TO_DATE(DAT_CANCELAMENTO_FAT, 'ddMMMyyyy:HH:mm:ss')         AS DAT_CANCELAMENTO_FAT,
    TO_DATE(DAT_ORIGINAL_VCTO_FAT,'ddMMMyyyy:HH:mm:ss')         AS DAT_ORIGINAL_VCTO_FAT,
    TO_DATE(DAT_ALTERACAO_VCTO_FAT,'ddMMMyyyy:HH:mm:ss')        AS DAT_ALTERACAO_VCTO_FAT,
    TO_DATE(DAT_CRIACAO_FAT,'ddMMMyyyy:HH:mm:ss')               AS DAT_CRIACAO_FAT,
    TO_DATE(DAT_VENCIMENTO_FAT,'ddMMMyyyy:HH:mm:ss')            AS DAT_VENCIMENTO_FAT,
    to_date(to_timestamp(DAT_STATUS_FAT, 'ddMMMyyyy:HH:mm:ss')) AS DAT_STATUS_FAT,
    date_format(to_timestamp(DAT_STATUS_FAT, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_STATUS_FAT,
    to_date(to_timestamp(DAT_MIN_VENCIMENTO_FAT, 'ddMMMyyyy:HH:mm:ss')) AS DAT_MIN_VENCIMENTO_FAT,
    date_format(to_timestamp(DAT_MIN_VENCIMENTO_FAT, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_MIN_VENCIMENTO_FAT,

    CAST(NUM_BILL_SEQ_FAT AS INT)                                AS NUM_BILL_SEQ_FAT,
    CAST(NUM_SEQ_ACORDO_FAT AS INT)                              AS NUM_SEQ_ACORDO_FAT,

    CAST(IND_ISENCAO_COB_FAT AS STRING)                          AS IND_ISENCAO_COB_FAT,
    CAST(IND_WO AS STRING)                                       AS IND_WO,
    CAST(IND_PDD AS STRING)                                      AS IND_PDD,
    CAST(IND_PCCR AS STRING)                                     AS IND_PCCR,
    CAST(IND_ACA AS STRING)                                      AS IND_ACA,
    CAST(IND_PRIMEIRA_FAT AS STRING)                             AS IND_PRIMEIRA_FAT,
    CAST(IND_FRAUDE AS STRING)                                   AS IND_FRAUDE,

    CAST(VAL_FAT_LIQUIDO AS DECIMAL(18,2))                       AS VAL_FAT_LIQUIDO,
    CAST(VAL_FAT_BRUTO AS DECIMAL(18,2))                         AS VAL_FAT_BRUTO,
    CAST(VAL_FAT_CREDITO AS DECIMAL(18,2))                       AS VAL_FAT_CREDITO,
    CAST(VAL_FAT_AJUSTE AS DECIMAL(18,2))                        AS VAL_FAT_AJUSTE,
    CAST(VAL_FAT_BRUTO_BC AS DECIMAL(18,2))                      AS VAL_FAT_BRUTO_BC,
    CAST(VAL_FAT_PAGAMENTO_BRUTO AS DECIMAL(18,2))               AS VAL_FAT_PAGAMENTO_BRUTO,
    CAST(VAL_FAT_ABERTO AS DECIMAL(18,2))                        AS VAL_FAT_ABERTO,
    CAST(VAL_FAT_ABERTO_LIQ AS DECIMAL(18,2))                    AS VAL_FAT_ABERTO_LIQ,
    CAST(VAL_MULTA_JUROS AS DECIMAL(18,2))                       AS VAL_MULTA_JUROS,
    CAST(VAL_MULTA_CANCELAMENTO AS DECIMAL(18,2))                AS VAL_MULTA_CANCELAMENTO,
    CAST(VAL_PARC_APARELHO_LIQ AS DECIMAL(18,2))                 AS VAL_PARC_APARELHO_LIQ,
    CAST(VAL_FAT_LIQ_JM_MC AS DECIMAL(18,2))                     AS VAL_FAT_LIQ_JM_MC,

    to_date(to_timestamp(DAT_ATIVACAO_CONTA_CLI, 'ddMMMyyyy:HH:mm:ss')) AS DAT_ATIVACAO_CONTA_CLI,
    date_format(to_timestamp(DAT_ATIVACAO_CONTA_CLI, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_ATIVACAO_CONTA_CLI,
    to_date(to_timestamp(DAT_CRIACAO_DW, 'ddMMMyyyy:HH:mm:ss')) AS DAT_CRIACAO_DW,
    date_format(to_timestamp(DAT_CRIACAO_DW, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_CRIACAO_DW
FROM raw_base_atraso
""")
df_trusted_atraso.createOrReplaceTempView("trusted_base_atraso")
#df_trusted_atraso.cache()

#print(log(), "Registros Trusted:", df_trusted_atraso.count())
#df_trusted_atraso.#printSchema()
#df_trusted_atraso.show(5, truncate=False)

"""# Join com a dimensão tipo de faturamento"""

df_trusted_atraso_refined = spark.sql("""
SELECT
    at.*,
    CAST(tf.DW_TIPO_FATURAMENTO AS STRING) AS DIM_TIPO_FATURAMENTO,
    CAST(tf.DSC_TIPO_FATURAMENTO AS STRING) AS DSC_TIPO_FATURAMENTO,
    CAST(tf.COD_TIPO_FATURAMENTO AS STRING) AS COD_TIPO_FATURAMENTO,
    to_date(to_timestamp(tf.DAT_EXPIRACAO_DW, 'ddMMMyyyy:HH:mm:ss')) AS DIM_DAT_EXPIRACAO_DW,                              -- Renaming to avoid conflict
    date_format(to_timestamp(tf.DAT_EXPIRACAO_DW, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_DIM_DAT_EXPIRACAO_DW,  -- New column for time component
    to_date(to_timestamp(tf.DAT_CRIACAO_DW, 'ddMMMyyyy:HH:mm:ss')) AS DIM_DAT_CRIACAO_DW,                                  -- Renaming to avoid conflict
    date_format(to_timestamp(tf.DAT_CRIACAO_DW, 'ddMMMyyyy:HH:mm:ss'),'HH:mm:ss') AS HR_DIM_DAT_CRIACAO_DW,      -- New column for time component
    CAST(tf.DSC_TIPO_FATURAMENTO_ABREV AS STRING) AS DSC_TIPO_FATURAMENTO_ABREV
FROM trusted_base_atraso at
LEFT JOIN df_tipo_faturamento tf
ON at.dw_tipo_faturamento = tf.dw_tipo_faturamento

""")

df_trusted_atraso_refined.createOrReplaceTempView("lake_atraso_refined")

#print(log(), "Registros Trusted:", df_trusted_atraso_refined.count())
#df_trusted_atraso_refined.#printSchema()
#df_trusted_atraso_refined.show(5, truncate=False)

"""# Salvar na camada Trusted"""


#print("Trusted path:", path_trusted)

df_trusted_atraso_refined.write \
    .partitionBy("ts_proc_partition") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(bucket_trusted_atraso)

"""# Controle de carga"""

df_controle_atraso = spark.sql (f"""
SELECT
    '{output_trusted_atraso}' AS name_file,
    ts_proc,
    ts_proc_partition,
    count(*) as qtd_registros
from lake_atraso_refined
    GROUP BY 1,2,3
""")

#df_controle_atraso.show()

"""# Controle de processamento"""

path_control_atraso = os.path.join(bucket_control_atraso, f'tb_controle_processamento_{output_trusted_atraso}_{PROCESS_DATE}')
#print("Control path:", path_control_atraso)

df_controle_atraso.write \
  .mode('append') \
  .option('compression', 'snappy') \
  .parquet(path_control_atraso)