# -*- coding: utf-8 -*-
"""Trusted_base_telco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfgoFAqb_OZ82X97iEuM06OoG_bjULHy

# Iniciando o Spark
"""

from pyspark.sql import SparkSession
import os
import pytz
from datetime import datetime

spark = SparkSession.builder.appName("Trusted_base_telco").getOrCreate()

"""# Importando bibliotecas"""

import os
import sys
import pytz
import numpy as np
import datetime
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext
from pyspark.sql.functions import udf, lpad, translate
from datetime import datetime
from datetime import timedelta
from datetime import date
from dateutil.relativedelta import relativedelta
from pyspark.sql.types import *
from pyspark.sql.functions import count, avg

"""#Funções auxiliares e variáveis"""

# Função de log
def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') + " >>>"

# Timestamp de processamento (com hora/minuto/segundo)
agora = datetime.now(pytz.timezone('America/Sao_Paulo'))
dthproc = agora.strftime("%Y%m%d%H%M%S")

# Data da execução (AAAAmmdd)
PROCESS_DATE = datetime.now().strftime("%Y%m%d")

# Período de referência (AAAAmm)
REF_PERIOD = datetime.now().strftime("%Y%m")

# Buckets e nomes de saída
bucket_trusted = f"s3://meu-bucket/{PROCESS_DATE}/0003_trusted"
bucket_raw = f"s3://meu-bucket/{PROCESS_DATE}/0002_raw"
bucket_control = f"s3://meu-bucket/{PROCESS_DATE}/0005_control"
output_trusted = "trusted_base_telco"

# Prints para conferência
print("PROCESS_DATE:", PROCESS_DATE)
print("REF_PERIOD:", REF_PERIOD)
print("dthproc:", dthproc)
print("bucket_trusted:", bucket_trusted)
print("bucket_raw:", bucket_raw)
print("bucket_control:", bucket_control)

"""#  Leitura da camada Raw"""

raw_path = os.path.join(bucket_raw , "base_telco")
df_raw = spark.read.parquet(raw_path)
df_raw.createOrReplaceTempView("raw_base_telco")

print(log(), "Registros na Raw:", df_raw.count())
df_raw.show(5, truncate=False)

df_Trusted_base_telco = spark.read.parquet(raw_path)
df_Trusted_base_telco.createOrReplaceTempView("df_Trusted_base_telco")

"""#  Análise de frequência de colunas"""

# decidir se ira colocar essa parte no projeto, pode usar processamento desnecessario
#def Freq(pTabela, pColuna):
    qtd_total = pTabela.count()
    pTabela.createOrReplaceTempView("tab_input")

    frq = spark.sql(f"""
        SELECT
            {pColuna},
            COUNT(*) AS qtd_absoluto,
            ROUND(100*(COUNT(*) / {qtd_total}),2) AS qtd_percentual
        FROM tab_input
        GROUP BY {pColuna}
        ORDER BY {pColuna}
    """)

    qtd = frq.count()
    print("Quantidade de domínios:", qtd)
    if qtd > 500:
        frq.show(1000, truncate=False)
        return "Domínio muito granular"
    else:
        frq.show(qtd, truncate=False)
        print("Volumetria total:", qtd_total)
        return "Freq da coluna " + pColuna

# Exemplo de uso
Freq(df_Trusted_base_telco, "SAFRA_ANO")
Freq(df_Trusted_base_telco, "IsSetup")

"""# Leitura dos dados na camada Raw"""

raw_path = os.path.join(bucket_raw, "base_telco")
df_raw = spark.read.parquet(raw_path)
df_raw.createOrReplaceTempView("raw_base_telco")

print(log(), "Registros na Raw:", df_raw.count())
df_raw.show(5, truncate=False)

"""# Processamento tipagem para camada Trusted"""

df_trusted = spark.sql(f"""
    SELECT
        ref,
        ref_partition,
        {dthproc} AS ts_proc,
        {dthproc} AS ts_proc_partition,
        CAST(NUM_CPF AS STRING) AS NUM_CPF,
        CAST(SAFRA AS INT) AS SAFRA,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 1, 4) AS INT) AS SAFRA_ANO,
        CAST(SUBSTRING(CAST(SAFRA AS STRING), 5, 2) AS INT) AS SAFRA_MES,
        CAST(FLAG_INSTALACAO AS BOOLEAN) AS IsSetup,
        CAST(FPD AS BOOLEAN) AS IsFPD,
        CAST(PROD AS STRING) AS ProductDescription,
        CAST(flag_mig2 AS STRING) AS ProductMigration,
        {",".join([f"CAST(var_{i} AS FLOAT) AS Var{i}" for i in range(26,94)])}
    FROM raw_base_telco
""")

df_trusted.createOrReplaceTempView("lake")
df_trusted.cache()

print(log(), "Registros Trusted:", df_trusted.count())
df_trusted.printSchema()
df_trusted.show(5, truncate=False)

"""# Salvar na camada Trusted"""

path_trusted = os.path.join(bucket_trusted, output_trusted)
print("Trusted path:", path_trusted)

df_trusted.write \
    .partitionBy("SAFRA,ref_partition","ts_proc_partition") \
    .mode("overwrite") \
    .option("compression", "snappy") \
    .parquet(path_trusted)

"""# Controle de carga"""

controle = spark.sql(f"""
    SELECT
        '{output_trusted}' AS name_file,
        ref,
        ref_partition,
        ts_proc,
        ts_proc_partition,
        COUNT(*) AS qtd_registros
    FROM lake
    GROUP BY 1,2,3,4,5
""")

controle.createOrReplaceTempView("controle")
controle.cache()

print(log(), "Registros controle:", controle.count())
controle.show(truncate=False)

"""# Controle de processamento"""

path_control = os.path.join(bucket_control, "tb_0002_controle_procesamento_trusted")
print("Control path:", path_control)

controle.write \
    .mode("append") \
    .option("compression", "snappy") \
    .parquet(path_control)